### ISSUE TITLE
com.mopub.common.MoPubBrowser has leaked window

### ISSUE THREAD

**Issue by myrmidon-media** [mopub/mopub-android-sdk#114]
Sometimes I get his error:

``` log
09-25 15:00:06.493: E/WindowManager(3346): android.view.WindowLeaked: Activity com.mopub.common.MoPubBrowser has leaked window android.widget.ZoomButtonsController$Container{42a1ce88 V.E..... ......I. 0,0-768,97} that was originally added here
09-25 15:00:06.493: E/WindowManager(3346):  at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
09-25 15:00:06.493: E/WindowManager(3346):  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
09-25 15:00:06.493: E/WindowManager(3346):  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
09-25 15:00:06.493: E/WindowManager(3346):  at android.widget.ZoomButtonsController.setVisible(ZoomButtonsController.java:371)
09-25 15:00:06.493: E/WindowManager(3346):  at com.android.org.chromium.android_webview.AwZoomControls.invokeZoomPicker(AwZoomControls.java:29)
09-25 15:00:06.493: E/WindowManager(3346):  at com.android.org.chromium.content.browser.ContentViewCore.invokeZoomPicker(ContentViewCore.java:2818)
09-25 15:00:06.493: E/WindowManager(3346):  at com.android.org.chromium.content.browser.ContentViewGestureHandler$1.onScroll(ContentViewGestureHandler.java:380)
09-25 15:00:06.493: E/WindowManager(3346):  at com.android.org.chromium.content.browser.third_party.GestureDetector.onTouchEvent(GestureDetector.java:588)
09-25 15:00:06.493: E/WindowManager(3346):  at com.android.org.chromium.content.browser.ContentViewGestureHandler.processTouchEvent(ContentViewGestureHandler.java:957)
09-25 15:00:06.493: E/WindowManager(3346):  at com.android.org.chromium.content.browser.ContentViewGestureHandler.confirmTouchEvent(ContentViewGestureHandler.java:1007)
09-25 15:00:06.493: E/WindowManager(3346):  at com.android.org.chromium.content.browser.ContentViewCore.confirmTouchEvent(ContentViewCore.java:1363)
09-25 15:00:06.493: E/WindowManager(3346):  at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
09-25 15:00:06.493: E/WindowManager(3346):  at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
09-25 15:00:06.493: E/WindowManager(3346):  at android.os.Handler.dispatchMessage(Handler.java:102)
09-25 15:00:06.493: E/WindowManager(3346):  at android.os.Looper.loop(Looper.java:136)
09-25 15:00:06.493: E/WindowManager(3346):  at android.app.ActivityThread.main(ActivityThread.java:5001)
09-25 15:00:06.493: E/WindowManager(3346):  at java.lang.reflect.Method.invokeNative(Native Method)
09-25 15:00:06.493: E/WindowManager(3346):  at java.lang.reflect.Method.invoke(Method.java:515)
09-25 15:00:06.493: E/WindowManager(3346):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
09-25 15:00:06.493: E/WindowManager(3346):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
09-25 15:00:06.493: E/WindowManager(3346):  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by twkx** [comment]
Crap, I got this error too... I'm using SDK 3.5.0
