### ISSUE TITLE
NullPointerException in MraidVideoPlayerActivity.onDestroy

### ISSUE THREAD

**Issue by robbypond** [mopub/mopub-android-sdk#125]
I received this stacktrace through Crashlytics.

java.lang.RuntimeException: Unable to destroy activity 
Caused by: java.lang.NullPointerException
       at com.mopub.mobileads.MraidVideoPlayerActivity.onDestroy(MraidVideoPlayerActivity.java:60)
       at android.app.Activity.performDestroy(Activity.java:5273)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1110)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3438)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3469)
       at android.app.ActivityThread.access$1200(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5041)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by MoJRen** [comment]
this has been fixed in 3.3
