### ISSUE TITLE
NullPointerException in LocationService.java

### ISSUE THREAD

**Issue by myrmidon-media** [mopub/mopub-android-sdk#145]
This is the backtrace:

``` log
java.lang.NullPointerException
       at android.os.Parcel.readException(Parcel.java:1431)
       at android.os.Parcel.readException(Parcel.java:1379)
       at android.location.ILocationManager$Stub$Proxy.getLastLocation(ILocationManager.java:649)
       at android.location.LocationManager.getLastKnownLocation(LocationManager.java:1144)
       at com.mopub.common.LocationService.getLastKnownLocation(LocationService.java:63)
       at com.mopub.common.AdUrlGenerator.setLocation(AdUrlGenerator.java:58)
       at com.mopub.mobileads.WebViewAdUrlGenerator.generateUrlString(WebViewAdUrlGenerator.java:36)
       at com.mopub.mobileads.AdViewController.generateAdUrl(AdViewController.java:433)
       at com.mopub.mobileads.AdViewController.internalLoadAd(AdViewController.java:193)
       at com.mopub.mobileads.AdViewController.loadAd(AdViewController.java:176)
       at com.mopub.mobileads.MoPubView.loadAd(MoPubView.java:118)
       at com.mopub.mobileads.MoPubInterstitial.load(MoPubInterstitial.java:66)
       at com.myapp.android.BaseActivity.h(BaseActivity.java:386)
       at com.myapp.android.BaseActivity$b.handleMessage(BaseActivity.java:100)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5041)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

To solve it:

``` java

LocationManager locationManager = (LocationManager) context.getSystemService(Context.LOCATION_SERVICE);
Location gpsLocation = null;

/* Check if locationManager is available on device */
if(locationManager == null){
        return null;
}

```

**Comment by joeblubaugh** [comment]
Hi @pablo-navarro . Do you have any information about the devices you've seen this error on?

**Comment by pablo-navarro** [comment]
Hi,

We are using crashalytics and it says that the devices are mostly android boxes running 4.2.2.

One of them is a MEGA 268 TV, the others are unknown for crashalytics.

We think is a bug on the android framework installed in these devices, the only way we found to work around it is with a try catch NullPointerException. The above solution we posted didn't  work.
