### ISSUE TITLE
NullPointerException at com.mopub.mobileads.MoPubActivity.onCreate(MoPubActivity.java:99)

### ISSUE THREAD

**Issue by nathantsoi** [mopub/mopub-android-sdk#146]
seen on
- nexus 5 android 4.4.2
- galaxy nexus 4.1.1

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mopub.mobileads.MoPubActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2259)
       at android.app.ActivityThread.access$800(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
       at android.os.Handler.dispatchMessage(Handler.java:122)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5122)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at com.mopub.mobileads.MoPubActivity.onCreate(MoPubActivity.java:99)
       at android.app.Activity.performCreate(Activity.java:5437)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1092)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2259)
       at android.app.ActivityThread.access$800(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
       at android.os.Handler.dispatchMessage(Handler.java:122)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5122)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by ekhaliul** [comment]
Getting a similar crash. It seems to be caused by assigning null value of mBroadcastIdentifier to 'long'. If I understand correctly the activity should be started for interstitial ads, but I intentionally did not load any interstitial ads, so that might be the cause of the problem. Patch below seem to eliminate the crash. 
```
+++ BaseInterstitialActivity.java	2015-03-30 20:15:39.000000000 -0700
@@ -40,7 +40,7 @@
     }
 
     private CloseableLayout mCloseableLayout;
-    private Long mBroadcastIdentifier;
+    private long mBroadcastIdentifier=-1L;
 
     public abstract View getAdView();
 
@@ -89,11 +89,11 @@
         mCloseableLayout.setCloseVisible(false);
     }
 
-    protected static Long getBroadcastIdentifierFromIntent(Intent intent) {
+    protected static long getBroadcastIdentifierFromIntent(Intent intent) {
         if (intent.hasExtra(BROADCAST_IDENTIFIER_KEY)) {
             return intent.getLongExtra(BROADCAST_IDENTIFIER_KEY, -1L);
         }
-        return null;
+        return -1L;
     }
 
     @Nullable
```

**Comment by mntgoat** [comment]
I have the same exception. Will try the above patch. 
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{mypackage/com.mopub.mobileads.MoPubActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5041)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at com.mopub.mobileads.MoPubActivity.onCreate(MoPubActivity.java:92)
       at android.app.Activity.performCreate(Activity.java:5104)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5041)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
