### ISSUE TITLE
[3.7.0] NPE in MoPubBrower

### ISSUE THREAD

**Issue by danijoo** [mopub/mopub-android-sdk#166]
Hello,

Im using mopub version 3.7 and get reports of the following NPE via crashlytics. Its only happening rarely though. I wasnt able to reproduce it yet.

```
compile('com.mopub.sdk.android:mopub:3.7.0@aar') {
        transitive = true;
    }
```

```
java.lang.NullPointerException
       at com.android.internal.policy.impl.PhoneWindow.updateProgressBars(PhoneWindow.java:1416)
       at com.android.internal.policy.impl.PhoneWindow.onIntChanged(PhoneWindow.java:1358)
       at com.android.internal.policy.impl.PhoneWindow.updateInt(PhoneWindow.java:3644)
       at com.android.internal.policy.impl.PhoneWindow.setFeatureInt(PhoneWindow.java:1303)
       at android.app.Activity.setProgress(Activity.java:4703)
       at com.mopub.common.MoPubBrowser$2.onProgressChanged(MoPubBrowser.java:137)
       at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:518)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:177)
       at android.app.ActivityThread.main(ActivityThread.java:4947)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by waninkoko** [comment]
I'm getting reports of this exact issue using SDK 3.8.0

Looks like this is not happening with AOSP.

**Comment by edwardho** [comment]
Hello danijoo and waninkoko,

It seems that the setProgress activity is null when onProgressChanged(WebView webView, int progress) is called, throwing the NPE. Please see our source code [here](https://github.com/mopub/mopub-android-sdk/blob/10b5f6c37fd8f409b8ded1d84ad4a3081dacab27/mopub-sdk/src/main/java/com/mopub/common/MoPubBrowser.java#L137).

I have found a possible solution here on [stackoverflow] (http://stackoverflow.com/questions/23833547/null-pointer-exception-while-using-onprogresschanged-inside-fragment) where you write an if statement to check whether the activity is null and only follow through if the activity is not null.

From the stackoverflow comments, this NPE may result when the method is called when the activity is no longer visible. Could you write into support@mopub.com so we can investigate to see when this error occurs?

Please note that the MoPub Github Issue Reporting Section will now be housed directly on the Twitter Developer Community Forum as this Issue Reporting Section will be closed on June 30th.

Please visit https://twittercommunity.com/c/fabric/mopub for any additional support questions or feel free to email support@mopub.com for further support regarding this issue.

Thank you for your patience and understanding.

Edward
