### ISSUE TITLE
Mopub native video crashing

### ISSUE THREAD

**Issue by alinus-ciruvin** [mopub/mopub-android-sdk#292]
mopub native video crashing

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Please list all relevant steps to reproduce the observed behavior.
trying to show native video in activity

#### Environment setup
In our app we are using exoplayer version 2.9.1 and mopub sdk version 5.4.1 (latest) which uses exoplayer dependency version 2.8.2. When we try to render mopub native video ads it throw exception because HttpDiskCompositeDataSource does not have method addTransferListener() which is added in new exoplayer.

#### Expected behavior:
Should be able to see video ad

#### Observed behavior:
Crashed app

#### Evidence:
java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.upstream.DataSource.addTransferListener(com.google.android.exoplayer2.upstream.TransferListener)"

    at com.google.android.exoplayer2.source.ExtractorMediaSource.createPeriod(ExtractorMediaSource.java:379)

    at com.google.android.exoplayer2.MediaPeriodHolder.&lt;init&gt;(MediaPeriodHolder.java:82)

    at com.google.android.exoplayer2.MediaPeriodQueue.enqueueNextMediaPeriod(MediaPeriodQueue.java:149)

    at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1530)

    at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1399)

    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:513)

    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)

    at android.os.Handler.dispatchMessage(Handler.java:102)

    at android.os.Looper.loop(Looper.java:164)

    at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by chauduyphanvu1** [comment]
@alinus-ciruvin, thanks for the report. I'll relay this to the rest of the team and discuss updating ExoPlayer in the MoPub SDK. I'll let you know when it's resolved!

Vu Chau
MoPub SDK Team

**Comment by rsatrasala** [comment]
This information is logged internally. Please watch our SDK change logs for updates.
