### ISSUE TITLE
IndexOutOfBoundsException when running native ads

### ISSUE THREAD

**Issue by louistsaitszho** [mopub/mopub-android-sdk#293]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Evidence: Hundreds of crash report on Crashlytics that looks like this
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 14(offset:80).state:17 not.a.real.app.widget.EmptyViewRecyclerView{960f439 VFED.V... ......ID 0,0-1080,1792 #7f0a0334 app:id/recycler_view}, adapter:com.mopub.nativeads.MoPubRecyclerAdapter@5c78a7e, layout:android.support.v7.widget.LinearLayoutManager@d9c8bdf, context:not.a.real.app.home.HomeActivity@90ac05a
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:5923)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:5858)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:5854)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(SourceFile:2230)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(SourceFile:1557)
       at android.support.v7.widget.LinearLayoutManager.fill(SourceFile:1517)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(SourceFile:612)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(SourceFile:3875)
       at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile:3639)
       at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(SourceFile:1888)
       at android.support.v7.widget.RecyclerView$1.run(SourceFile:407)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
       at android.view.Choreographer.doCallbacks(Choreographer.java:790)
       at android.view.Choreographer.doFrame(Choreographer.java:718)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

I am not sure if this is gonna help or not, but [this SO answer](https://stackoverflow.com/a/37110764) suggest clearing out the `RecycledViewPool` before performing `notifyDataSetChanged` in 

- [L101](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/mopub-sdk-native-static/src/main/java/com/mopub/nativeads/MoPubRecyclerAdapter.java#L101)
- [L121](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/mopub-sdk-native-static/src/main/java/com/mopub/nativeads/MoPubRecyclerAdapter.java#L121)
- [L140](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/mopub-sdk-native-static/src/main/java/com/mopub/nativeads/MoPubRecyclerAdapter.java#L140)
- [L158](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/mopub-sdk-native-static/src/main/java/com/mopub/nativeads/MoPubRecyclerAdapter.java#L158)

**Comment by dravyan** [comment]
Hello @louistsaitszho,
 Thank you for reporting this. I tried to test native ads using MoPub sample app with SDK 5.3 and also with latest MoPub SDK 5.4.1 and I do not notice the issue reported above. Could you please share the steps to replicate the issue or provide us complete sample project you are using to replicate the above behavior?. Also can you upgrade the SDK to latest and try?.

Thanks,
Dravya Nataraj
MoPubSDK Team

**Comment by louistsaitszho** [comment]
@dravyan We are still trying to reproduce it on our end, but from what we know, it only affect our non-paying users which sees the ad. We will definitely be upgrading the MoPub SDK, and we will also add a bunch of extra logging to try to reproduce it, but meanwhile, can you guys take a look at the SDK and see if the suggestion above makes sense or not? 

Thanks!

**Comment by dravyan** [comment]
@louistsaitszho Unfortunately we will not be able to confirm until we are able to reproduce the issue reported on our end. Hence please provide us the sample project once you are able to replicate the issue.

Thanks.
Dravya Nataraj
MoPubSDK Team

**Comment by rsatrasala** [comment]
Unable to reproduce the issue. Please re-open if there are additional details available.

**Comment by carlos-ferreira** [comment]
I'm having the same issue as well with the latest SDK version.
I admin it's very very hard to reproduce, but it happens.
I believe the issue happens when :
- MoPubRecyclerAdapter inserts an ad on the recyclerview, recyclerview "thinks" it has one more item;
- User scrolls;
- Recyclerview tries to get viewholder for position that's beyond the dataset item count and crashes.

A solution could be adding logs to MoPubRecyclerAdapter to try to detect a pattern

**Comment by carlos-ferreira** [comment]
@rsatrasala Can you please re-open ?
I'm facing this issue as well.


Stacktrace:

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionPostHolder{b759560 position=4 id=-1, oldPos=3, pLpos:3 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{f29ec1 VFED.V... ......I. 0,0-720,1140 #7f0901b2 app:id/post_list}, adapter:com.mopub.nativeads.MoPubRecyclerAdapter@df29666, layout:com.bloggerpro.android.base.ui.recyclerview.NPALinearLayoutManager@3014da7, context:com.bloggerpro.android.app.features.mainscreen.MainActivity@b1f3114
       at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5974)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4085)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3849)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
       at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
       at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1887)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:898)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1077)
       at android.view.View.layout(View.java:22406)
       at android.view.ViewGroup.layout(ViewGroup.java:6594)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3399)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2868)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1916)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8554)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by chauduyphanvu** [comment]
@carlos-ferreira, are you able to reproduce the crash in-house using a local app? If so, could you share that app with us so we can investigate? Feel free to include all the steps necessary to trigger the crash.

Vu Chau
MoPub Team

**Comment by carlos-ferreira** [comment]
@chauduyphanvu I'm able to reproduce the issue with live ads, but with test ads i cannot.

In order to test this i have an app that has a recyclerview and when you reach the bottom of the list it loads more items. 

It contains 10 items per load, so when you reach the end of the list it loads more 10 items.
The way i do it to trigger the crash is:
- Start the app;
- App loads 10 items;
- Scroll up and down for a while until the app crashes.

It's hard to trigger the crash but i have 100% sure it's due to the MopubRecylerAdapter.
I know this because if i go to mopub.com and disable ads i get zero crashes on recyclerviews.

I believe the issue is related to the getAdjustedCount method on MopubRecyclerAdapter, because when the recyclerview crashes, it's after calling getItemCount.

The method getItemCount from the adapter is called on the following recyclerview methods that throw the exceptions i'm experiencing:

![image](https://user-images.githubusercontent.com/472873/70855270-62e5c180-1ec0-11ea-9b4d-ed63b69be6ca.png)

![image](https://user-images.githubusercontent.com/472873/70855299-a7715d00-1ec0-11ea-8511-b1a46787c529.png)

Please let me know if i can help more on this.

**Comment by chauduyphanvu** [comment]
@carlos-ferreira, thanks for sharing the details! Are you able to reproduce that crash in our Android sample app or your own app? If so, could you share your integration code (preferably in a compilable project)? Thanks!
