### ISSUE TITLE
NoClassDefFoundError: Cannot resolve "org.apache.http.client.utils.URLEncodedUtils" in Android P

### ISSUE THREAD

**Issue by waninkoko** [mopub/mopub-android-sdk#294]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.4.1

#### Device model and OS Version:
Any device with Android 9

#### Ad Unit IDs used in reproducing the issue:
Any

#### Steps to reproduce the behavior:
Load an ad in an Android 9 device within an app that targets SDK 28

#### Expected behavior:
The SDK should function correctly and not produce a crash

#### Observed behavior:
A crash occurs due to a ```NoClassDefFoundError``` because the class ```org.apache.http.client.utils.URLEncodedUtils``` cannot be resolved in Android 9 if the app targets SDK 28. This information, and a workaround for now, can be found here: https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p

#### Evidence:
```Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/client/utils/URLEncodedUtils;
       at com.mopub.mraid.MraidBridge.handleShouldOverrideUrl(SourceFile:316)
       at com.mopub.mraid.MraidBridge$5.shouldOverrideUrlLoading(SourceFile:274)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77)
       at aBg.a(SourceFile:1)
       at xy.b(SourceFile:81)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(SourceFile:148)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)```

**Comment by waninkoko** [comment]
Nevermind. Just found out I was looking at the wrong crash report (related to SDK 5.2.0, not 5.4.1 which has this issue fixed). Closing...
