### ISSUE TITLE
TransactionTooLargeException

### ISSUE THREAD

**Issue by 2math** [mopub/mopub-android-sdk#302]
One line summary of the issue here
The app crashes when attemps to open Interstitial ad

- [ X ] I am submitting a bug report for existing functionality
- [ X ] I visited https://developers.mopub.com/ and found no answer
- [ X ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ X ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.4.1
#### Device model and OS Version:
Nexus 5x OS 8.1
#### Ad Unit IDs used in reproducing the issue:
edb524cb982349fe9292632e04c87b34
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
The MoPubInterstitial is ready. The app calls mInterstitial.show() before to load a specific fragment.
And waits for InterstitialAdListener.onInterstitialDismissed to load the fragment.

#### Expected behavior:
As concisely as possible, describe the expected behavior.
The app shows the Interstitial ad.

#### Observed behavior:
As concisely as possible, describe the observed behavior.
The app crashes on mInterstitial.show()

#### Evidence:
Device log files, Network log file, etc.

2019-01-23 16:37:44.067 E/ActivityManager: Second failure launching bg.sega.android/com.mopub.mobileads.MoPubActivity, giving up
    android.os.TransactionTooLargeException: data parcel size 640532 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:764)
        at android.app.IApplicationThread$Stub$Proxy.scheduleLaunchActivity(IApplicationThread.java:1216)
        at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1457)
        at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:974)
        at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:7152)
        at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:7219)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:291)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2919)
        at android.os.Binder.execTransact(Binder.java:697)

I assume that in MoPubActivity.start() String htmlData could be more than 512kb and leads to that crash

**Comment by dravyan** [comment]
@2math , thanks for reporting this. We are trying to replicate the issue internally using mopub sample app and I am getting no fill every time we try and load the adunit `edb524cb982349fe9292632e04c87b34`. Are you able to load the same adunit consistently?.

Thanks,
Dravya

**Comment by 2math** [comment]
Hi @dravyan , thanks for your quick response.
Last night the client has stopped the adunit I posted first, because it was crashing the production app.
He created a simillar adunit to test on my side "954136656063405e852766e3f4071c41" .
It has 50% fill rate and it crashes the same way :(.
I have to mention that there are some interstatial ads that are showing correct(I guess they are smaller).
Also when I use the test adunit provided in the documentation "24534e1901884e398f1253216226017e" is all good too.

I have cloned the sample app from here and tested with same adunit and had the same crash on 3th time ad shown (first 2 was OK).

Here are the logs from the sample app crash :

2019-01-24 08:24:06.863 557-557/com.mopub.simpleadsdemo D/MoPub: Successfully hit tracking endpoint: https://ads.mopub.com/m/attempt
2019-01-24 08:24:06.951 557-557/com.mopub.simpleadsdemo I/chromium: [INFO:CONSOLE(37)] "document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.", source: http://ads.mopub.com/ (37)
2019-01-24 08:24:07.093 557-557/com.mopub.simpleadsdemo I/chromium: [INFO:CONSOLE(146)] " [  0.001s] [studio.sdk] ", source: https://s0.2mdn.net/ads/studio/Enabler.js (146)
2019-01-24 08:24:07.257 557-557/com.mopub.simpleadsdemo I/chromium: [INFO:CONSOLE(146)] " [  0.167s] [studio.sdk] Using default ad parameters in test environment. Simulating local events.", source: https://s0.2mdn.net/ads/studio/Enabler.js (146)
2019-01-24 08:24:07.298 557-557/com.mopub.simpleadsdemo D/MoPub Sample App: Interstitial loaded.
2019-01-24 08:24:07.413 557-557/com.mopub.simpleadsdemo I/chromium: [INFO:CONSOLE(50)] "Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': '#https://segabg.com/a/300x250_SpaceCallenges/gwd-taparea_1' is not a valid selector.", source: http://ads.mopub.com/ (50)

2019-01-24 08:24:09.027 3652-4298/? E/ActivityManager: Transaction too large, intent: Intent { flg=0x10000000 cmp=com.mopub.simpleadsdemo/com.mopub.mobileads.MoPubActivity (has extras) }, extras size: 637880, icicle size: 0
2019-01-24 08:24:09.028 3652-4298/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 640568)
2019-01-24 08:24:09.029 3652-4298/? W/ActivityManager: Exception when starting activity com.mopub.simpleadsdemo/com.mopub.mobileads.MoPubActivity
    android.os.TransactionTooLargeException: data parcel size 640568 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:764)
        at android.app.IApplicationThread$Stub$Proxy.scheduleLaunchActivity(IApplicationThread.java:1216)
        at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1457)
        at com.android.server.am.ActivityStackSupervisor.startSpecificActivityLocked(ActivityStackSupervisor.java:1579)
        at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2726)
        at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2255)
        at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:2093)
        at com.android.server.am.ActivityStack.completePauseLocked(ActivityStack.java:1486)
        at com.android.server.am.ActivityStack.activityPausedLocked(ActivityStack.java:1413)
        at com.android.server.am.ActivityManagerService.activityPaused(ActivityManagerService.java:7441)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:317)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2919)
        at android.os.Binder.execTransact(Binder.java:697)
2019-01-24 08:24:09.030 3652-3668/? W/zygote64: kill(-557, 9) failed: No such process
2019-01-24 08:24:09.030 3652-4298/? W/ActivityManager: Force removing ActivityRecord{e13c4fc u0 com.mopub.simpleadsdemo/.MoPubSampleActivity t19713}: app died, no saved state
2019-01-24 08:24:09.032 990-990/? I/cr_ChildProcessService: Destroying ChildProcessService pid=990
2019-01-24 08:24:09.046 3652-4298/? I/ActivityManager: Start proc 1027:com.mopub.simpleadsdemo/u0a334 for activity com.mopub.simpleadsdemo/com.mopub.mobileads.MoPubActivity
2019-01-24 08:24:09.047 1027-1027/? I/zygote64: Late-enabling -Xcheck:jni
2019-01-24 08:24:09.050 3652-3666/? I/ActivityManager: Killing 990:com.android.chrome:sandboxed_process3/u0a334i494 (adj 0): isolated not needed

2019-01-24 08:24:09.112 3652-9136/? E/ActivityManager: Transaction too large, intent: Intent { flg=0x10000000 cmp=com.mopub.simpleadsdemo/com.mopub.mobileads.MoPubActivity (has extras) }, extras size: 637880, icicle size: 0
2019-01-24 08:24:09.113 3652-9136/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 640568)
2019-01-24 08:24:09.114 3652-9136/? E/ActivityManager: Second failure launching com.mopub.simpleadsdemo/com.mopub.mobileads.MoPubActivity, giving up
    android.os.TransactionTooLargeException: data parcel size 640568 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:764)
        at android.app.IApplicationThread$Stub$Proxy.scheduleLaunchActivity(IApplicationThread.java:1216)
        at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1457)
        at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:974)
        at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:7152)
        at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:7219)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:291)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2919)
        at android.os.Binder.execTransact(Binder.java:697)
2019-01-24 08:24:09.114 3652-9136/? I/ActivityManager: Process com.mopub.simpleadsdemo (pid 1027) has died: fore TOP 
2019-01-24 08:24:09.118 3652-3668/? W/zygote64: kill(-557, 9) failed: No such process
2019-01-24 08:24:09.118 3652-3668/? I/zygote64: Successfully killed process cgroup uid 10334 pid 557 in 88ms
2019-01-24 08:24:09.118 3652-3668/? W/zygote64: Failed to open process cgroup uid 99494 pid 990: No such file or directory
2019-01-24 08:24:09.118 3652-3668/? E/zygote64: Error encountered killing process cgroup uid 99494 pid 990: No such file or directory
2019-01-24 08:24:09.118 3652-3668/? W/zygote64: kill(-1027, 9) failed: No such process
2019-01-24 08:24:09.127 3652-9136/? I/ActivityManager: Start proc 1041:com.mopub.simpleadsdemo/u0a334 for activity com.mopub.simpleadsdemo/com.mopub.mobileads.MoPubActivity
2019-01-24 08:24:09.128 1041-1041/? I/zygote64: Late-enabling -Xcheck:jni
2019-01-24 08:24:09.145 3652-3668/? W/zygote64: kill(-1027, 9) failed: No such process
2019-01-24 08:24:09.146 3652-3668/? I/zygote64: Successfully killed process cgroup uid 10334 pid 1027 in 27ms
2019-01-24 08:24:09.173 1041-1048/? E/zygote64: Failed sending reply to debugger: Broken pipe
2019-01-24 08:24:09.179 3652-32023/? I/ActivityManager: Killing 31689:com.android.vending:instant_app_installer/u0a34 (adj 906): empty #17
2019-01-24 08:24:09.180 3652-3668/? W/zygote64: kill(-31689, 9) failed: No such process
2019-01-24 08:24:09.186 1041-1048/? I/zygote64: Debugger is no longer active
2019-01-24 08:24:09.225 3652-3668/? W/zygote64: kill(-31689, 9) failed: No such process
2019-01-24 08:24:09.311 3652-3652/? W/NotificationService: Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@cdd003d in package com.mopub.simpleadsdemo
2019-01-24 08:24:09.317 3652-3652/? W/WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@11a682a
2019-01-24 08:24:09.268 3652-3668/? I/chatty: uid=1000(system) ActivityManager identical 1 line
2019-01-24 08:24:09.311 3652-3668/? W/zygote64: kill(-31689, 9) failed: No such process
2019-01-24 08:24:09.343 427-427/? D/SurfaceFlinger: duplicate layer name: changing com.google.android.googlequicksearchbox/com.google.android.launcher.GEL to com.google.android.googlequicksearchbox/com.google.android.launcher.GEL#1
2019-01-24 08:24:09.355 3652-3668/? W/zygote64: kill(-31689, 9) failed: No such process
2019-01-24 08:24:09.384 3652-3668/? W/zygote64: kill(-31689, 9) failed: No such process
2019-01-24 08:24:09.384 3652-3668/? I/zygote64: Successfully killed process cgroup uid 10034 pid 31689 in 204ms
2019-01-24 08:24:09.470 30401-30452/? I/RunnerModule: Event Bus thread priority is now -2

**Comment by dravyan** [comment]
@2math thank you. We are looking into this. I will notify once I have an update.

Thanks,
Dravya Nataraj
MoPub SDK Team

**Comment by dravyan** [comment]
@2math This issue has been addressed internally. We got a fix and will be releasing it in the upcoming SDK. Please watch our SDK release updates.

Thanks,
Dravya Nataraj
MoPub SDK Team

**Comment by chauduyphanvu1** [comment]
This should be fixed as of v5.6.0 of the Android SDK. Please update to that version and let us know if you continue seeing the issue!
