### ISSUE TITLE
Mopub Native Video Crash With ExoPlayer 

### ISSUE THREAD

**Issue by Hassanova** [mopub/mopub-android-sdk#340]
App Crashes when i try to display simple Mopub native video Ad.

We are using ExoPlayer V2.10.2 in our app, while Mopub is using an older Version of ExoPlayer v2.9.5 which cause a conflict. 

Are you planning to release a version with the latest ExoPlayer release ? is there anyway to workaround this issue ?  

 I am submitting a bug report for existing functionality
  I visited https://developers.mopub.com/ and found no answer
  I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
  I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
display mopub native video inside a simple activity

#### Expected behavior:
Video ad should be loaded and displayed correctly 

#### Observed behavior:
App crashes 

#### Evidence:
java.lang.NoSuchMethodError: No static method newInstance([Lcom/google/android/exoplayer2/Renderer;Lcom/google/android/exoplayer2/trackselection/TrackSelector;Lcom/google/android/exoplayer2/LoadControl;)Lcom/google/android/exoplayer2/ExoPlayer; in class Lcom/google/android/exoplayer2/ExoPlayerFactory; or its super classes (declaration of 'com.google.android.exoplayer2.ExoPlayerFactory' appears in /data/app/com.sample.app-1nESkG2RVVbFOSrn_5L4Pg==/base.apk!classes15.dex)

#### Log:
2019-07-02 14:43:50.330 21371-21371/com.sample.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sample.app, PID: 21371
    java.lang.NoSuchMethodError: No static method newInstance([Lcom/google/android/exoplayer2/Renderer;Lcom/google/android/exoplayer2/trackselection/TrackSelector;Lcom/google/android/exoplayer2/LoadControl;)Lcom/google/android/exoplayer2/ExoPlayer; in class Lcom/google/android/exoplayer2/ExoPlayerFactory; or its super classes (declaration of 'com.google.android.exoplayer2.ExoPlayerFactory' appears in /data/app/com.sample.app-1nESkG2RVVbFOSrn_5L4Pg==/base.apk!classes15.dex)
        at com.mopub.nativeads.NativeVideoController$MoPubExoPlayerFactory.newInstance(NativeVideoController.java:512)
        at com.mopub.nativeads.NativeVideoController.preparePlayer(NativeVideoController.java:410)
        at com.mopub.nativeads.NativeVideoController.prepare(NativeVideoController.java:277)
        at com.mopub.nativeads.MoPubCustomEventVideoNative$MoPubVideoNativeAd.render(MoPubCustomEventVideoNative.java:582)
        at com.mopub.nativeads.MoPubVideoNativeAdRenderer.renderAdView(MoPubVideoNativeAdRenderer.java:61)
        at com.mopub.nativeads.MoPubVideoNativeAdRenderer.renderAdView(MoPubVideoNativeAdRenderer.java:21)
        at com.mopub.nativeads.NativeAd.renderAdView(NativeAd.java:166)
        at com.sample.app.client.adapter.ArticlesCustomAdapter.displayMoPubNative(ArticlesCustomAdapter.java:5002)
        at com.sample.app.client.adapter.ArticlesCustomAdapter.onBindViewHolder(ArticlesCustomAdapter.java:2805)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6929)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6971)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5891)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5997)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5993)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2227)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:613)
        at com.sample.app.support.MyLinearLayoutManager.onLayoutChildren(MyLinearLayoutManager.java:34)
        at com.sample.app.client.fragments.ArticlesFragment$1.onLayoutChildren(ArticlesFragment.java:373)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4029)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3746)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1884)
        at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:409)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1079)
        at android.view.Choreographer.doCallbacks(Choreographer.java:885)
        at android.view.Choreographer.doFrame(Choreographer.java:806)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1065)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by dravyan** [comment]
@Hassanova,
Thank you for reporting this issue. I will notify this to the rest of the team and we will discuss to update the ExoPlayer to the latest. I will let you know once it is resolved.

Thanks,
Dravya Nataraj
MoPub SDK Team

**Comment by Hassanova** [comment]
Thank you @dravyan for your response. Yes, you are right this will not help because this is actually the problem. Gradle updates ExoPlayer version to 2.10.2 while Mopub is trying to use some methods from an older version of ExoPlayer. 

This issue could be resolved if i downgraded  ExoPlayer version to the one that Mopub is using (v2.9.5 ). but unfortunately i can't do that.

**Comment by dravyan** [comment]
@Hassanova ,
This issue is resolved in MoPub SDK 5.9.0. ExoPlayer is updated to 2.10.3 in the latest [release](https://github.com/mopub/mopub-android-sdk/releases/tag/v5.9.0). 

Thanks,
Dravya Nataraj
MoPub SDKTeam

**Comment by Hassanova** [comment]
@dravyan 
Thank you. This issue is resolved after upgrading to v5.9.0.
