### ISSUE TITLE
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by billyking991** [mopub/mopub-android-sdk#345]
I'm getting a com.mopub.mobileads.AdViewController crash, both in the Google Play beta testing and in the live app.  It looks to be coming from MoPub Banner View, but I didn't see this happening before 5.7.1 (at least not on 5.5.0).

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.7.1 and 5.8.0

#### Android Studio Version:
3.4.1

#### Gradle Version:
3.2.1 (Upgrading screws everything up)

#### Device model and OS Version:
a6eltespr
heroqltevzw
j3xlteatt 
a50 
Others listed by Google Play

#### Ad Unit IDs used in reproducing the issue:
Not sure

#### Steps to reproduce the behavior:
This is mostly happening during the Google Play beta testing.

#### Expected behavior:
Shouldn't crash?

#### Observed behavior:
Crashes are showing up on the Google Play Developer Console

#### Evidence:
java.lang.IllegalStateException: 
  at android.view.ViewGroup.addViewInner (ViewGroup.java:5247)
  at android.view.ViewGroup.addView (ViewGroup.java:5078)
  at android.view.ViewGroup.addView (ViewGroup.java:5050)
  at com.mopub.mobileads.AdViewController$3.run (AdViewController.java:643)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6981)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
FATAL EXCEPTION: ControllerMessenger
Process: com.williamking.whattheforecast, PID: 29205
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
  at android.view.ViewGroup.addViewInner(ViewGroup.java:5122)
  at android.view.ViewGroup.addView(ViewGroup.java:4953)
  at android.view.ViewGroup.addView(ViewGroup.java:4925)
  at com.mopub.mobileads.AdViewController$3.run(AdViewController.java:643)
  at android.os.Handler.handleCallback(Handler.java:789)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
  at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:166)
  at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:158)
  at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:138)
  at androidx.test.espresso.action.Tap$1.a(Tap.java:6)
  at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:20)
  at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
  at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
  at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
  at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at android.os.Handler.handleCallback(Handler.java:789)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:6938)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Please let me know if you need anything else.  I'm sort fo going crazy trying to figure out if this is real or not.  

Thank you!

**Comment by hmertkahraman** [comment]
Hi @billyking991,

Thanks for reaching us out on this and the information you provide. This problem seems to be associated with a **banner** creative type's request, could you confirm?

Also can you confirm that you're not trying to inject any view inside of the MoPubView at any time?

It seems that the AdViewController is attempting to inject the banner view into a parent container (MoPubView), while Android OS realizes MoPubView already has something in it (potentially an outstanding banner view, or something else). However with the given crash log, it is hard to determine the flow, and we cannot repro it on our end.

If you can explain the view hierarchy you constructed around this MoPubView, and AdViewController, and the code snippets that operate the ad request, show lifecycle, we can assist you further.

Please let us know.

Thanks,
MoPub Team

**Comment by billyking991** [comment]
Thank you for getting back to me.  This is definitely with a banner ad.  

In my layout file, I have this:

<RelativeLayout
        android:id="@+id/footerLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:gravity="bottom"
        android:background="#000000"
        android:layout_alignParentBottom="true">

        <com.mopub.mobileads.MoPubView
            android:id="@+id/adview"
            android:layout_width="fill_parent"
            android:layout_height="50dp" />

</RelativeLayout>

Then in my activity file, I call the ad like this:

MoPubView moPubView = findViewById(R.id.adview);
moPubView.setAdUnitId("a8e36e8ccfac480186609851b45147ee");
moPubView.loadAd();
moPubView.setBannerAdListener(MainActivity.this);

My app has been set up the same way for two years and this is the first time I had this issue appear.  The crashes aren't happening in large numbers, but they are happening in the live app.  The Google Beta Testing was what initially brought it to my attention.  I feel like it started happening when I upgraded to 5.7.1 and 5.8.0.

Thank you for your help with this.

**Comment by hmertkahraman** [comment]
Hi @billyking991 ,

Thanks for the follow up with details. Would you be able to investigate to see if you experienced this issue before upgrading to 5.8 (in 5.7.1 or below)? Moreover, how often is this error raised from your live apps on the Google Beta Testing, all runs, or occasionally, and if so frequently or rarely?

**This would help us determine the source of the problem and help you faster.**

Thanks,
Mert

**Comment by billyking991** [comment]
I have some additional info.  It looks like it may be coming from UnityAds, which I also have in my project.  This all started happening after I added UnityAds to my project.  Here is the trace that I'm getting from Android Studio:

I/chromium: [INFO:CONSOLE(0)] "Uncaught (in promise) [object Array]", source: file:///storage/emulated/0/Android/data/com.xxxxxxxxx.xxxxxxxxxxxxx/cache/UnityAdsCache/UnityAdsWebApp.html?platform=android&origin=https%3A%2F%2Fwebview.unityads.unity3d.com%2Fwebview%2F3.2.0%2Fb536f67619a9d59f8c23c3d4366d3abfc8d8237d%2Frelease%2Findex.html&version=b536f67619a9d59f8c23c3d4366d3abfc8d8237d (0)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.williamking.whattheforecast, PID: 15180
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5034)
        at android.view.ViewGroup.addView(ViewGroup.java:4865)
        at android.view.ViewGroup.addView(ViewGroup.java:4837)
        at com.mopub.mobileads.AdViewController$3.run(AdViewController.java:661)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/XLogExceptionHandler: defaultHandler = com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler@3571422
    thread = Thread[main,5,main], exception = java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
W/System: A resource failed to call end. 

I'm using UnityAds and adapters:
implementation 'com.unity3d.ads:unity-ads:3.2.0'
implementation 'com.mopub.mediation:unityads:3.2.0.0'

Could it be an adapter issue?  I've just reproduced this issue using a debug app and each time, I get the exact trace I've pasted above.  Thoughts?

**Comment by hmertkahraman** [comment]
Hi @billyking991, 

Could you please try to observe if this issue is happening while the banner is trying to refresh (after the default 30 seconds interval)? 
Such that: Initial banner loads, then after ~30 seconds, the banner tries to refresh, and this issue occurs.

Thanks,
Mert

**Comment by haianhsing** [comment]
I also have the problem while I add the UnityAds banner as a adapter. It seem that while the banner is trying to refresh and if the result is a UnityAds banner , it somtime crash.

**Comment by hmertkahraman** [comment]
Hi @haianhsing,

Thanks for the information. We will investigate the issue further and get back to you.

Mert

**Comment by billyking991** [comment]
I apologize for the delay in getting back to you.  I didn't get the notification that you had responded.  Yes, if I wait longer than 30 seconds to leave and come back to the MainActivity, it's not an issue.  If I launch the app initially, leave to another Activity and come back before 30 seconds, it is not an issue anymore.

**Comment by ImADevelloper** [comment]
I have the exact same issue with Unity Ads banners through MoPub.
And I can reproduce it : 

- Force the Unity Ads to test mode (or put it in test mode in the code)
- Only put Unity Ads ON for banner in the corresponding segment on your MoPub account

- Open the app, MoPub is not able to find a Unity banner ad an fail to load it (no crash)
- Close the app
- Open the app again, MoPub find a Unity banner ad and it's displayed
- Close the app
- Open the app again, MoPub find a Unity banner ad and CRASH!

(it also did it with live banner but it's more difficult to tell because the fill rate is not that good. So we can't tell if the first step (MoPub is not able to find a Unity banner ad an fail to load it) is cause of the fill rate or not)

Other infos :
Mopub 5.8.0
Unity Ads 3.2.0
MoPub Unity Ads Adaptater for Mediation 1.1.3
Android 9
Device : Samsung S10

**Comment by hmertkahraman** [comment]
Hi @haianhsing ,

We're still looking into this issue and will advise.
cc: @ImADevelloper , @billyking991 

Thanks,
Mert

**Comment by BianconeroIle** [comment]
Hi @chauduyphanvu 

I got the same problems and i think it's trigged by this.

Fatal Exception: java.lang.IllegalArgumentException
Scrapped or attached views may not be recycled. isScrap:false isAttached:true com.packagename.RecyclerView{21d95c1c VFED.V.. ........ 0,0-540,840 #7f0a03a7 app:id/recycler_view}, adapter:com.mopub.nativeads.MoPubRecyclerAdapter@1da577d7, layout:androidx.recyclerview.widget.LinearLayoutManager@1141b8c4, 

Any clue? 

Ilija

**Comment by chauduyphanvu** [comment]
@BianconeroIle, I'm hesitant to say it is the same issue because your log shows `IllegalArgumentException` while the original issue reported is an `IllegalStateException`.

What's your banner implementation like? Are there more details to that trace? If you can reproduce that exception locally, could you send over a zipped project with which you saw the exception? Thank you!

**Comment by Sergey-Kulyk** [comment]
@chauduyphanvu I have the same issue. Please fix it because I have this problem on production.
I use: 
gms -> 18.1.1
unity adapter -> 3.2.0.1
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4636)
        at android.view.ViewGroup.addView(ViewGroup.java:4477)
        at android.view.ViewGroup.addView(ViewGroup.java:4417)
        at android.view.ViewGroup.addView(ViewGroup.java:4390)
        at com.google.android.gms.internal.ads.zzcln.onSuccess(com.google.android.gms:play-services-ads@@18.1.1:17)
        at com.google.android.gms.internal.ads.zzdch.run(com.google.android.gms:play-services-ads@@18.1.1:13)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.google.android.gms.internal.ads.zzczj.zzb(com.google.android.gms:play-services-ads-lite@@18.1.1:7)
        at com.google.android.gms.internal.ads.zzatp.zzb(com.google.android.gms:play-services-ads@@18.1.1:8)
        at com.google.android.gms.internal.ads.zzczj.dispatchMessage(com.google.android.gms:play-services-ads-lite@@18.1.1:5)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6816)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)

**Comment by chauduyphanvu** [comment]
Does anyone have a chance to share a mini project with source code with which they saw this crash so we can investigate it further?

**Comment by xiaocong** [comment]
> So it looks like the crash comes from [this line](https://github.com/mopub/mopub-android-sdk/blob/v5.7.1/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/mobileads/AdViewController.java#L643) in the 5.7.1 MoPub Android SDK, where a child view is attempted to be added to the existing `MoPubView` instance from the app. However, if you check the line right above, there's already a call to `removeAllViews()`, which should empty the `MoPubView's` hierarchy. On paper, then, this crash should not happen at all, because your `MoPubView` should always be empty to add a new child view (i.e. when a new banner is about to load).
> 

@chauduyphanvu the exception occurs because the child view already has a parent. I believe [this method](https://github.com/mopub/mopub-android-sdk/blob/v5.7.1/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/mobileads/AdViewController.java#L631)  was called twice for the same child view(maybe `HtmlBannerWebView`) which should be added into `MoPubView`.

**Comment by chauduyphanvu** [comment]
@xiaocong, that's what we suspect as well based on the call stack. However, see that there is a `moPubView.removeAllViews()` call right below, which should remove all the existing children Views. 

Do you have a sample project that exhibits this crash as well? If so, could you share it so we can take a look at the implementation?

**Comment by rsatrasala** [comment]
Closing due to inactivity.
