### ISSUE TITLE
Android 9.0 view.View.getRootWindowInsets()' on a null object reference

### ISSUE THREAD

**Issue by Winny-Wiky** [mopub/mopub-android-sdk#365]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.WindowInsets android.view.View.getRootWindowInsets()' on a null object reference
        at com.mopub.mobileads.MoPubInterstitial.updatedInsets(MoPubInterstitial.java:295)
        at com.mopub.mobileads.MoPubInterstitial.attemptStateTransition(MoPubInterstitial.java:151)
        at com.mopub.mobileads.MoPubInterstitial.attemptStateTransition(MoPubInterstitial.java:116)
        at com.mopub.mobileads.MoPubInterstitial.load(MoPubInterstitial.java:305)

Mopub SDK Version: 5.10.0, 5.9.0, 5.8.0

**Comment by chauduyphanvu** [comment]
@Winny-Wiky, thanks for letting us know about the exception! We'll check internally what we can do to prevent it from happening. In the meantime, if you reproduce that exception locally with your app, could you share the app with us for testing purposes?

Vu Chau
MoPub Team

**Comment by Winny-Wiky** [comment]
@chauduyphanvu, I'm integrating mopub in a unity game, ads load when I start the game,  it works well in under Android 9.0，but it will produce NullPointerException in Android 9.0. I guess it maybe  the unityplayer view isn't ready, you can try to test it, thanks.

**Comment by chauduyphanvu** [comment]
Closing as there has been no repro case.
