### ISSUE TITLE
Interstitial ads causing exception 

### ISSUE THREAD

**Issue by pm-vishal-chougule** [mopub/mopub-android-sdk#366]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

1. Load interstitial ad.
2. Destroy interstitial ad without showing it.
3. Can replicate in MoPub Sample App.

Exception: 
2019-12-06 20:25:38.970 29261-29261/com.mopub.simpleadsdemo W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.f(PG:314)
        at org.chromium.android_webview.AwContents.a(PG:288)
        at org.chromium.android_webview.AwContents.a(PG:591)
        at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(PG:272)
        at android.webkit.WebView.evaluateJavascript(WebView.java:1113)
        at com.moat.analytics.mobile.mpub.j.g(Unknown Source:34)
        at com.moat.analytics.mobile.mpub.j.d(Unknown Source:28)
        at com.moat.analytics.mobile.mpub.j.e(Unknown Source:0)
        at com.moat.analytics.mobile.mpub.j$2.onReceive(Unknown Source:2)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-12-06 20:25:38.978 29261-29261/com.mopub.simpleadsdemo I/chatty: uid=10089(com.mopub.simpleadsdemo) identical 5 lines
2019-12-06 20:25:38.980 29261-29261/com.mopub.simpleadsdemo W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.f(PG:314)
        at org.chromium.android_webview.AwContents.a(PG:288)
        at org.chromium.android_webview.AwContents.a(PG:591)
        at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(PG:272)
        at android.webkit.WebView.evaluateJavascript(WebView.java:1113)
        at com.moat.analytics.mobile.mpub.j.g(Unknown Source:34)
        at com.moat.analytics.mobile.mpub.j.d(Unknown Source:28)
        at com.moat.analytics.mobile.mpub.j.e(Unknown Source:0)
        at com.moat.analytics.mobile.mpub.j$2.onReceive(Unknown Source:2)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-12-06 20:25:39.155 29261-29261/com.mopub.simpleadsdemo W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.f(PG:314)
        at org.chromium.android_webview.AwContents.a(PG:288)
        at org.chromium.android_webview.AwContents.a(PG:591)
        at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(PG:272)
        at android.webkit.WebView.evaluateJavascript(WebView.java:1113)
        at com.moat.analytics.mobile.mpub.j.g(Unknown Source:34)
        at com.moat.analytics.mobile.mpub.j.d(Unknown Source:28)
        at com.moat.analytics.mobile.mpub.j.e(Unknown Source:0)
        at com.moat.analytics.mobile.mpub.j$2.onReceive(Unknown Source:2)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-12-06 20:25:39.166 29261-29261/com.mopub.simpleadsdemo I/chatty: uid=10089(com.mopub.simpleadsdemo) identical 1 line

#### Expected behavior: Should not throw exception 
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

2019-12-06 20:25:38.970 29261-29261/com.mopub.simpleadsdemo W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.f(PG:314)
        at org.chromium.android_webview.AwContents.a(PG:288)
        at org.chromium.android_webview.AwContents.a(PG:591)
        at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(PG:272)
        at android.webkit.WebView.evaluateJavascript(WebView.java:1113)
        at com.moat.analytics.mobile.mpub.j.g(Unknown Source:34)
        at com.moat.analytics.mobile.mpub.j.d(Unknown Source:28)
        at com.moat.analytics.mobile.mpub.j.e(Unknown Source:0)
        at com.moat.analytics.mobile.mpub.j$2.onReceive(Unknown Source:2)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-12-06 20:25:38.978 29261-29261/com.mopub.simpleadsdemo I/chatty: uid=10089(com.mopub.simpleadsdemo) identical 5 lines
2019-12-06 20:25:38.980 29261-29261/com.mopub.simpleadsdemo W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.f(PG:314)
        at org.chromium.android_webview.AwContents.a(PG:288)
        at org.chromium.android_webview.AwContents.a(PG:591)
        at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(PG:272)
        at android.webkit.WebView.evaluateJavascript(WebView.java:1113)
        at com.moat.analytics.mobile.mpub.j.g(Unknown Source:34)
        at com.moat.analytics.mobile.mpub.j.d(Unknown Source:28)
        at com.moat.analytics.mobile.mpub.j.e(Unknown Source:0)
        at com.moat.analytics.mobile.mpub.j$2.onReceive(Unknown Source:2)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-12-06 20:25:39.155 29261-29261/com.mopub.simpleadsdemo W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.f(PG:314)
        at org.chromium.android_webview.AwContents.a(PG:288)
        at org.chromium.android_webview.AwContents.a(PG:591)
        at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(PG:272)
        at android.webkit.WebView.evaluateJavascript(WebView.java:1113)
        at com.moat.analytics.mobile.mpub.j.g(Unknown Source:34)
        at com.moat.analytics.mobile.mpub.j.d(Unknown Source:28)
        at com.moat.analytics.mobile.mpub.j.e(Unknown Source:0)
        at com.moat.analytics.mobile.mpub.j$2.onReceive(Unknown Source:2)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-12-06 20:25:39.166 29261-29261/com.mopub.simpleadsdemo I/chatty: uid=10089(com.mopub.simpleadsdemo) identical 1 line

**Comment by chauduyphanvu** [comment]
Hi @pm-vishal-chougule, thanks for letting us know! We'll check internally what we can do to prevent this exception in the first place. Having said that, your integration should be OK. This exception does not affect the ad experience.

Vu Chau
MoPub Team

**Comment by pm-vishal-chougule** [comment]
Any updates??

**Comment by chauduyphanvu** [comment]
@pm-vishal-chougule, could you confirm whether this exception crashes the app? We were able to determine that the origin of the exception comes from the Moat SDK (`com.moat.analytics.mobile.mpub.j.g` in the stack trace). We will reach out to Moat to inform them of it—meanwhile, there should be no negative impact on your app or ad experience.

**Comment by pm-vishal-chougule** [comment]
Thanks for the update,  i does not crashes app but every time we call destroy without showing ad it show the exception.

**Comment by chauduyphanvu** [comment]
@pm-vishal-chougule, we've informed the Moat team of this exception. Once they've addressed that in their SDK, we will include it in the next MoPub SDK release.

This exception does not have any negative impact on your app or ad experience.
