### ISSUE TITLE
I am submitting a bug report for existing functionality

### ISSUE THREAD

**Issue by winitdevadmin** [mopub/mopub-android-sdk#378]
I am submitting a bug report for existing functionality

#### MoPub SDK Version:
5.10.0@aar

we followed exact versions of libraries based this commit of yours
https://github.com/mopub/mopub-android-sdk/commit/166b5666cf531647070657aa018efa8c1b57a331

#### Android Studio Version:
3.5.3

#### Gradle Version:
5.4.1

#### Device model and OS Version:
Mostly Galaxy s series - S9, S9+, S8 etc

LG K8(2018)
LG G6
LG Premier Pro

Moto Z(3)
Nexus 6
Moto G (5) Plus

48% Android 9
27% Android 8
15% Android 7
6% Android 10

#### Steps to reproduce the behavior:
No steps crashes as soon as it opens

#### Expected behavior:
Atleast need a way to throw errors instead of crashing on users

#### Observed behavior:
its crashing as soons as it loads, 
Either crashes on line FacebookAdRenderer.java:143 or FacebookAdRenderer.java:147

#### Evidence:
Fatal Exception: java.lang.ClassCastException: androidx.appcompat.widget.AppCompatImageView cannot be cast to com.facebook.ads.MediaView
       at com.mopub.nativeads.FacebookAdRenderer$FacebookNativeViewHolder.fromViewBinder(FacebookAdRenderer.java:143)
       at com.mopub.nativeads.FacebookAdRenderer.renderAdView(FacebookAdRenderer.java:54)
       at com.mopub.nativeads.FacebookAdRenderer.renderAdView(FacebookAdRenderer.java:24)
       at com.mopub.nativeads.NativeAd.renderAdView(NativeAd.java:166)
       at com.mopub.nativeads.MoPubStreamAdPlacer.bindAdView(MoPubStreamAdPlacer.java:433)
       at com.mopub.nativeads.MoPubRecyclerAdapter.onBindViewHolder(MoPubRecyclerAdapter.java:424)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
       at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
       at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at com.google.android.material.appbar.AppBarLayout.onLayout(AppBarLayout.java:270)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1042)
       at android.view.View.layout(View.java:22398)
       at android.view.ViewGroup.layout(ViewGroup.java:6577)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3363)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2827)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1873)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8478)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by chauduyphanvu** [comment]
@winitdevadmin, this crash is happening because your native ad template (XML) is using an ImageView to render the Facebook MediaView asset. Instead, please use the Facebook MediaView itself. It means you might need to have two separate .xml files - one for Facebook native ad creatives, and one for other ad networks.

Feel free to check out MoPub's sample ad layout for Facebook: https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sample/res/main/layout/native_ad_fan_list_item.xml#L47-L59.

Vu Chau
MoPub Team

**Comment by PallabJunior** [comment]
I faced the exact same issue. The exception is caused by the icon holder view in your fb ad layout xml file. You are probably using an ImageView for showing the ad icon for the native ad, just replace it with the com.facebook.ads.MediaView. Now you have two mediaviews both for the icon and the media content in the fb native ad layout.
