### ISSUE TITLE
Error receiving broadcast Intent android.net.conn.CONNECTIVITY_CHANGE

### ISSUE THREAD

**Issue by schmylan** [mopub/mopub-android-sdk#388]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.11.1.1
#### Android Studio Version:
3.6.1
#### Gradle Version:
3.6.1
#### Device model and OS Version:

Devices
* 52% samsung
* 19% motorola
* 7% Jlinksz
* 6% HTC
* 16% Other (11)

OS Versions
* 66% Android 4
* 26% Android 5
* 7% Android 9
* <1% Android 6
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

I am unable to recreate it myself but it began in my latest release which included MoPub mediaion. 
 Crashlytics says: 
> This issue has 560 crashes affecting 78 users

#### Expected behavior:
As concisely as possible, describe the expected behavior.

No crashes in Crashlytics.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

I'll attach the crash log below

#### Evidence:
Device log files, Network log file, etc.

```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in androidx.work.impl.constraints.trackers.NetworkStateTracker$NetworkStateBroadcastReceiver@17d106eb
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:969)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5696)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

```
Caused by java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@12674d96 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@27a3ed17[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:298)
       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
       at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:644)
       at androidx.work.impl.background.systemalarm.WorkTimer.startTimer(WorkTimer.java:82)
       at androidx.work.impl.background.systemalarm.DelayMetCommandHandler.onAllConstraintsMet(DelayMetCommandHandler.java:100)
       at androidx.work.impl.constraints.WorkConstraintsTracker.onConstraintMet(WorkConstraintsTracker.java:150)
       at androidx.work.impl.constraints.controllers.ConstraintController.updateCallback(ConstraintController.java:134)
       at androidx.work.impl.constraints.controllers.ConstraintController.onConstraintChanged(ConstraintController.java:141)
       at androidx.work.impl.constraints.trackers.ConstraintTracker.setState(ConstraintTracker.java:103)
       at androidx.work.impl.constraints.trackers.NetworkStateTracker$NetworkStateBroadcastReceiver.onReceive(NetworkStateTracker.java:170)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:950)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5696)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by chauduyphanvu** [comment]
@schmylan, we do not see mentions of MoPub's packages in the stack trace. Do you have any more info or stack traces?

Separately, do you know what happens in the app the moment leading up to the crash? Crashlytics lets you [record events](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android) to provide more context into the state of the app the moment before the crash.

Vu Chau
MoPub Team
