### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by OlegTarashkevich** [mopub/mopub-android-sdk#394]
Hi, 

@chauduyphanvu I receive 160 crashed only for last 3 months.

#### MoPub SDK Version:
5.12.0 (and lower)

#### Android Studio Version:
3.6.2

#### Gradle Version:
3.4.1

#### Device model and OS Version:
Many devices - Samsung, Huawei, Xiaomi, Motorola etc.

#### Ad Unit IDs used in reproducing the issue:
Is it secure to provide keys for public viewing?

#### Steps to reproduce the behavior:
I didn't see the crashes in my test devices, but I receive them in Crashlytics from other users.

#### Expected behavior:
Just don't crash the app.

#### Evidence:
`Fatal Exception: java.lang.NoSuchMethodError: No static method getMainExecutor(Landroid/content/Context;)Ljava/util/concurrent/Executor; in class Landroidx/core/a/a; or its super classes (declaration of 'androidx.core.a.a' appears in base.apk)
       at com.mopub.mobileads.VastVideoViewControllerTwo.createVideoView(VastVideoViewControllerTwo.java:352)
       at com.mopub.mobileads.VastVideoViewControllerTwo.<init>(VastVideoViewControllerTwo.java:184)
       at com.mopub.mobileads.MraidVideoPlayerActivity.createVideoViewController(MraidVideoPlayerActivity.java:130)
       at com.mopub.mobileads.MraidVideoPlayerActivity.onCreate(MraidVideoPlayerActivity.java:48)
       at android.app.Activity.performCreate(Activity.java:7955)
       at android.app.Activity.performCreate(Activity.java:7944)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3463)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7857)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)`

<img width="991" alt="Screen Shot 2020-05-10 at 11 55 50" src="https://user-images.githubusercontent.com/13828110/81495585-fe396200-92b9-11ea-8168-95a98cc87624.png">
<img width="982" alt="Screen Shot 2020-05-10 at 12 03 44" src="https://user-images.githubusercontent.com/13828110/81495590-02657f80-92ba-11ea-8078-c4bbe6ffb8ef.png">

**Comment by OlegTarashkevich** [comment]
Are any of the developers working on the SDK now?
I need a fix for this issue.

**Comment by ScottishPig** [comment]
Not a MoPub guy, but it looks like it might be a proguard issue. The SDK is trying to access a totally valid method ( [API reference](https://developer.android.com/reference/androidx/core/content/ContextCompat#getMainExecutor(android.content.Context)) ) and `androidx.core.content.ContextCompat` is being minified to `androidx.core.a.a` . Try disabling minification for your production build?

**Comment by chauduyphanvu** [comment]
@OlegTarashkevich, thanks for letting us know of the crash. Do you have the ad unit ID that serves the ad that triggers this crash? 

Along the lines of @ScottishPig's suggestion, it seems some Android classes are missing in the resulting APK. First of all, if you have Proguard turned on, try adding exceptions for that package name (`androidx.core`). Then, if you still see issues, make sure you include all the necessary SDKs/frameworks needed by MoPub. Refer to [this list](https://github.com/mopub/mopub-android-sdk#requirements) for the required third-party frameworks.

Vu Chau
MoPub Team

**Comment by OlegTarashkevich** [comment]
Thanks for the suggestions. I checked required third-party libraries and found that instead of v.1.1.0 I use "androidx.appcompat:appcompat:1.0.2" . I used 1.0.2 due to bugs in 1.1.0 related to webview in Android 5.

**Comment by chauduyphanvu** [comment]
@OlegTarashkevich, thanks for the update. Are you able to confirm if updating to appcompat v1.1.0 resolves this crash?

**Comment by OlegTarashkevich** [comment]
@chauduyphanvu Yes, I didn't receive any new crash. But only one day has passed since the publication of the app with appcompat v.1.1.0
Thanks for the help!
