### ISSUE TITLE
MoPub 5.13.+ does not work anymore on Java 7 and hide exception

### ISSUE THREAD

**Issue by TurpIF** [mopub/mopub-android-sdk#412]
MoPub 5.13.+ does not work anymore on Java 7 and hide exception

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:

5.13.0 and 5.13.1

#### Android Studio Version:

3.5.3

#### Gradle Version:

5.4.1

#### Device model and OS Version:

Emulator, any version

#### Ad Unit IDs used in reproducing the issue:

`b195f8dd8ded45fe847ad89ed1d016da ` the test AdUnit

#### Steps to reproduce the behavior:

* Create a new project without [Java 8 language feature support](https://developer.android.com/studio/write/java8-support#supported_features)
* Strictly follow [MoPub documentation](https://developers.mopub.com/publishers/android/integrate/)
* Initialize SDK with LogLevel.Debug
* Load any ad (the test ad for instance)
* Put a breakpoint here: https://github.com/mopub/mopub-android-sdk/blob/3a7bd85201cb9cc7c91b14505e2ba3d16bd67393/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/mobileads/AdViewController.java#L780

#### Expected behavior:

* Exception is fully logged, so we can identify that it is an error on SDK side, not on any adapter.
* MoPub documentation is updated to declare that Java 8 feature support is required.

#### Observed behavior:

* Logcat only contains: `I/MoPub: [com.mopub.mobileads.AdViewController][loadBaseAd] SDK Error Log - Error loading ad adapter, java.lang.reflect.InvocationTargetException` without anymore details
* MoPub documentation does not tell anything about Java 8 support.

#### Evidence:

Observed stacktrace when debugging and setting breakpoint:

```
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at com.mopub.mobileads.AdViewController.loadBaseAd(AdViewController.java:773)
	at com.mopub.mobileads.AdViewController.onAdLoadSuccess(AdViewController.java:190)
	at com.mopub.mobileads.AdViewController$1.onSuccess(AdViewController.java:158)
	at com.mopub.network.AdLoader.deliverResponse(AdLoader.java:323)
	at com.mopub.network.AdLoader.access$400(AdLoader.java:35)
	at com.mopub.network.AdLoader$1.onSuccessResponse(AdLoader.java:101)
	at com.mopub.network.MultiAdRequest.deliverResponse(MultiAdRequest.java:117)
	at com.mopub.network.MultiAdRequest.deliverResponse(MultiAdRequest.java:27)
	at com.mopub.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
	at com.mopub.mobileads.AdAdapter.<init>(AdAdapter.java:59)
	at com.mopub.mobileads.InlineAdAdapter.<init>(InlineAdAdapter.java:35)
	... 18 more
```

I really appreciate that MoPub want to push new langage features such as Java 8 or Kotlin. Although, documentation should be updated accordingly, and exception such as this one should not be silenced.

Regards,
Pierre

**Comment by RajSuvariya-InMobi** [comment]
+1

**Comment by chauduyphanvu** [comment]
@TurpIF, thanks for letting us know! We've updated our docs to add the Java 8 language feature.

As for the exception, the compiler shouldn't be breaking on this line if you are using the test ad unit ID: https://github.com/mopub/mopub-android-sdk/blob/3a7bd85201cb9cc7c91b14505e2ba3d16bd67393/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/mobileads/AdViewController.java#L780 

Could you elaborate on how that happened for you? I'm using our sample app and not getting it. I tried commenting out the Java 8 `sourceCompatibility` and the app expectedly crashes.

Vu Chau
MoPub Team

**Comment by TurpIF** [comment]
Thank you for updating your documentation so fast. I hope it will help people when updating to your last version.

About the exception, my concern is that, indeed the error is almost silent without any hint on what is going on.

I encountered this issue when updating a mediation adapter to fit to the last MoPub version. And when testing, ads were not showing not because of the adapter but because of the SDK. And the fact that the exception was silence and "hidden" make it harder to detect the root cause.

The version 5.13 involves breaking changes both for ad networks (via the new inline/full screen API) but also for publishers via this new Java 8 restrictions. Moreover publishers may just switch to 5.13 without any compilation errors making them miss bid opportunities and noticing this only after release.

Regards,
Pierre

**Comment by chauduyphanvu** [comment]
@TurpIF, thank you. If it's not convenient for you to share that adapter and your code, we will keep an eye out for any exceptions while certifying the adapters. If there is one, I'll make sure we bubble it up with the full details.

**Comment by TurpIF** [comment]
There is no issue to share the code, it is open-source: https://github.com/criteo/android-publisher-sdk-mopub-adapters
Tell me if I need to take any action.

**Comment by chauduyphanvu** [comment]
@TurpIF, thanks for the confirmation. While we aren't able to assist with third-party mediation adapters, we can check on this type of issue for you as soon as we run into it internally. 

Closing this issue now as documentation has been updated.
