### ISSUE TITLE
Mopub 5.13.1 java.lang.NullPointerException at MoPubFullscreen.java:182

### ISSUE THREAD

**Issue by filosov** [mopub/mopub-android-sdk#413]
After update apllications to 5.13.1 version I start receiving NullPointerException at MoPubFullscreen.java:182

- [ x ] I am submitting a bug report for existing functionality
- [ x ] I visited https://developers.mopub.com/ and found no answer
- [ x ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ x ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.13.1
#### Android Studio Version:
3.6.3
#### Gradle Version:
5.6.4
#### Device model and OS Version:
![Снимок экрана 2020-07-19 в 19 38 40](https://user-images.githubusercontent.com/770105/87880085-7f6a4f00-c9f7-11ea-881e-aa5a6c8a76f5.png)
#### Expected behavior:
SDK not crashed

#### Evidence:
Full stack trace:
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mopub.mobileads.AdLifecycleListener$InteractionListener.onAdFailed(com.mopub.mobileads.MoPubErrorCode)' on a null object reference
       at com.mopub.mobileads.MoPubFullscreen.lambda$preRender$0$MoPubFullscreen(MoPubFullscreen.java:182)
       at com.mopub.mobileads.-$$Lambda$MoPubFullscreen$3H3zkNFnaPQ4PqCgAa8VbWGmgJs.run(lambda)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6623)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`

I suppose crash appeared when app go to background and main activity has stopped. About 71% of all crashes appeared when app was in background mode.

**Comment by chauduyphanvu** [comment]
@filosov, thanks for letting us know! We're aware of this issue and will be addressing it in an upcoming SDK release. 

For background, this is happening when the ad expires at the 4-hour mark. Is there a way you can request and show your ads in a shorter time frame? If so, that should reduce the crash frequency in the meantime. 

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
This has been fixed in [v5.14.0](https://github.com/mopub/mopub-android-sdk/commit/e8b8d865535855dacd65fdf741e1c0d5b7797ca5). Update and let us know if you continue seeing the issue!
