### ISSUE TITLE
NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL      java.lang.RuntimeException: Bad URL 

### ISSUE THREAD

**Issue by RaufJavid** [mopub/mopub-android-sdk#425]
Hi...I am getting this error while loading the Interstitial ad:
----------------------
**SDK Using**

minSdkVersion 19
targetSdkVersion 30
implementation('com.mopub:mopub-sdk:5.13.1@aar') {
        transitive = true
}
implementation 'com.google.android.gms:play-services-base:17.4.0'
---------------------
**Error Appearing**

2020-09-06 15:57:02.008 25544-25621/com.utech.allinonevideodownloader E/cr_VariationsUtils: Failed reading seed file "/data/user/0/com.utech.allinonevideodownloader/app_webview/variations_seed_new": /data/user/0/com.utech.allinonevideodownloader/app_webview/variations_seed_new (No such file or directory)
2020-09-06 15:57:02.008 25544-25621/com.utech.allinonevideodownloader E/cr_VariationsUtils: Failed reading seed file "/data/user/0/com.utech.allinonevideodownloader/app_webview/variations_seed": /data/user/0/com.utech.allinonevideodownloader/app_webview/variations_seed (No such file or directory)
2020-09-06 15:57:02.624 25544-25544/com.utech.allinonevideodownloader E/myhdasbdhf: 1
2020-09-06 15:57:03.062 25544-25672/com.utech.allinonevideodownloader E/Volley: [1095] NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL 
    java.lang.RuntimeException: Bad URL 
        at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:143)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
     Caused by: java.net.MalformedURLException: no protocol: 
        at java.net.URL.<init>(URL.java:601)
        at java.net.URL.<init>(URL.java:498)
        at java.net.URL.<init>(URL.java:447)
        at com.mopub.volley.toolbox.HurlStack.executeRequest(HurlStack.java:87)
        at com.mopub.network.RequestQueueHttpStack.executeRequest(RequestQueueHttpStack.java:57)
        at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:91)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132) 
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
        at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:90) 
2020-09-06 15:57:04.471 25544-25682/com.utech.allinonevideodownloader E/eglCodecCommon: GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
2020-09-06 15:57:17.730 25544-25544/com.utech.allinonevideodownloader E/loged112211: Notificaion Channel Created!

--------------------------------------------------------------------------------------
**Ad Loading Code**
        

      

        MyMoPub().init(this, Constant.MoPub.INTERSTITIAL_AD_UNIT)
        Handler(Looper.getMainLooper()).postDelayed({
            initAds2()
        }, 200)

    private fun initAds2() {

        moPubInterstitial = MoPubInterstitial(this, Constant.MoPub.INTERSTITIAL_AD_UNIT)
        Log.d("MoPub", "Interstitial ad is loading.")
        moPubInterstitial.load()

        moPubInterstitialInterstitialAdListener =
            object : MoPubInterstitial.InterstitialAdListener {
                override fun onInterstitialLoaded(interstitial: MoPubInterstitial?) {
                    //Do something when insterstitial is loaded
                    Log.d("MoPub", "Interstitial ad is loaded.")

                    //Show the Ad if the Interstitial is loaded
                    yourAppsShowInterstitialMethod()
                }

                override fun onInterstitialShown(interstitial: MoPubInterstitial?) {
                    //Do something when insterstitial is shown
                    Log.d("MoPub", "Interstitial ad has show.")
                }

                override fun onInterstitialFailed(interstitial: MoPubInterstitial?,errorCode: MoPubErrorCode?) {
                    //Do something when insterstitial is failed
                    Log.d("MoPub", "Interstitial ad failed to load with error: $errorCode")
                }

                override fun onInterstitialDismissed(interstitial: MoPubInterstitial?) {
                    //Do something when insterstitial is dismissed
                    Log.d("MoPub", "Interstitial ad has dismissed.")
                }

                override fun onInterstitialClicked(interstitial: MoPubInterstitial?) {
                    //Do something when insterstitial is clicked
                    Log.d("MoPub", "Interstitial ad clicked.")
                }
            }

        moPubInterstitial.interstitialAdListener = moPubInterstitialInterstitialAdListener

    }

    private fun yourAppsShowInterstitialMethod() {
        if (moPubInterstitial.isReady) {
            moPubInterstitial.show()
        } else {
            // Caching is likely already in progress if `isReady()` is false.
            // Avoid calling `load()` here and instead rely on the callbacks on moPubInterstitialInterstitialAdListener
        }
    }

    override fun onDestroy() {
        // You must call this or the banner view may cause a memory leak.
        moPubInterstitial.destroy()
        super.onDestroy()
    }
------------
**MoPub SDK Initialization Code**
class MyMoPub {

    private lateinit var mPersonalInfoManager: PersonalInfoManager

    private lateinit var mContext: Context

    fun init(context: Context, adunit: String) {
        mContext = context
        val sdkConfiguration = SdkConfiguration.Builder(adunit)
            .withLogLevel(MoPubLog.LogLevel.DEBUG)
            .withLegitimateInterestAllowed(false)
            .build()
        MoPub.initializeSdk(mContext, sdkConfiguration, initSdkListener())
    }

    private fun initSdkListener(): SdkInitializationListener {
        return SdkInitializationListener {
            /* MoPub SDK initialized.
            Check if you should show the consent dialog here, and make your ad requests. */
            Log.d("MoPub", "MoPub SDK Initilized")
            GDPRConsent()
        }
    }

    private fun GDPRConsent() {
        mPersonalInfoManager = MoPub.getPersonalInformationManager()!!
        Log.d("MoPub", "This country covered by GDPR? ${mPersonalInfoManager.gdprApplies()}")
        if (mPersonalInfoManager.shouldShowConsentDialog()) {
            mPersonalInfoManager.loadConsentDialog(initDialogLoadListener())
        }
    }

    private fun initDialogLoadListener(): ConsentDialogListener {
        return object : ConsentDialogListener {
            override fun onConsentDialogLoaded() {
                mPersonalInfoManager.showConsentDialog()
            }

            override fun onConsentDialogLoadFailed(@NonNull moPubErrorCode: MoPubErrorCode) {
                Log.d("MoPub", "Consent dialog failed to load.")
            }
        }
    }
}

**Comment by p158276** [comment]
Hi @RaufJavid ,
Thanks for reaching out. May I have the ad unit id you currently test with? 
Are you able to 100% reproduce the same error?

Thanks,

Yoyo Lin 
MoPub Team
