### ISSUE TITLE
NullPointerException on Meizu devices

### ISSUE THREAD

**Issue by Farasy** [mopub/mopub-android-sdk#435]
One line summary of the issue here

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Not known - No Meizu device available

#### Observed behavior:
We see a lot of crashes on Meizu devices (Note 8, X8, M8, 16TH, all Android 8) when going to view a fullscreen interstitial.
Unfortunately we don't have the ability to reproduce that issue since we don't have any Meizu devices here. May a reader has a Meizu and can reproduce that.

#### Evidence:

> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.f.net/com.mopub.mobileads.MoPubFullscreenActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2960)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1729)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6758)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

> Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
       at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:152)
       at com.meizu.nightmode.MzNightModeManager.getPackageName(MzNightModeManager.java:1185)
       at com.meizu.nightmode.MzNightModeManager.filterBlackList(MzNightModeManager.java:203)
       at com.meizu.nightmode.MzNightModeManager.initWebViewSystemNightModeSwitch(MzNightModeManager.java:1316)
       at android.webkit.WebView.<init>(WebView.java:666)
       at android.webkit.WebView.<init>(WebView.java:591)
       at android.webkit.WebView.<init>(WebView.java:574)
       at android.webkit.WebView.<init>(WebView.java:561)
       at android.webkit.WebView.<init>(WebView.java:551)
       at com.mopub.mobileads.BaseWebView.<init>(BaseWebView.java:32)
       at com.mopub.mraid.MraidBridge$MraidWebView.<init>(MraidBridge.java:249)
       at com.mopub.mraid.MraidController.createWebView(MraidController.java:919)
       at com.mopub.mobileads.MoPubWebViewController.fillContent(MoPubWebViewController.java:83)
       at com.mopub.mobileads.FullscreenAdController.<init>(FullscreenAdController.java:170)
       at com.mopub.mobileads.MoPubFullscreenActivity.onCreate(MoPubFullscreenActivity.java:74)
       at android.app.Activity.performCreate(Activity.java:7054)
       at android.app.Activity.performCreate(Activity.java:7045)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1216)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6707)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by chauduyphanvu** [comment]
@Farasy, thanks for letting us know! From looking at the code, it appears the `context` passed to MoPub is `null` [on this line](https://github.com/mopub/mopub-android-sdk/blob/v5.13.1/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/mobileads/BaseWebView.java). Could you confirm if your app has a valid `context` when showing the interstitial ad (at around the time of the crash)?

Meanwhile, we'll see what we can do in this case to prevent this kind of crash.

Vu Chau
MoPub Team

**Comment by Farasy** [comment]
Thanks @chauduyphanvu 
The context is valid.

**Comment by chauduyphanvu** [comment]
Closing as irreproducible. Feel free to reopen if you are able to share your code.
