### ISSUE TITLE
IllegalArgumentException: class com.mopub.common.ViewabilityVendor declares multiple JSON fields named a

### ISSUE THREAD

**Issue by sinhpn92** [mopub/mopub-android-sdk#436]
I have got error issue in my report come to from MoPubFullscreen;

MoPub SDK Version: 5.14.0
The logs:
```
Fatal Exception: java.lang.IllegalArgumentException: class com.mopub.common.ViewabilityVendor declares multiple JSON fields named a
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:172)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
       at com.google.gson.Gson.getAdapter(Gson.java:458)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
       at com.google.gson.Gson.getAdapter(Gson.java:458)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
       at com.google.gson.Gson.getAdapter(Gson.java:458)
       at com.google.gson.Gson.toJson(Gson.java:696)
       at com.google.gson.Gson.toJson(Gson.java:683)
       at com.google.gson.Gson.toJson(Gson.java:638)
       at com.google.gson.Gson.toJson(Gson.java:618)
       at com.mopub.mobileads.VastVideoConfig.toJsonString(VastVideoConfig.java:642)
       at com.mopub.mobileads.MoPubFullscreen.onVastVideoConfigurationPrepared(MoPubFullscreen.java:283)
       at com.mopub.mobileads.VastManager.onAggregationComplete(VastManager.java:124)
       at com.mopub.mobileads.VastXmlManagerAggregator.onPostExecute(VastXmlManagerAggregator.java:141)
       at com.mopub.mobileads.VastXmlManagerAggregator.onPostExecute(VastXmlManagerAggregator.java:51)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.access$600(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7156)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

Have any suggest to solve this issue? Thank so much!

**Comment by chauduyphanvu** [comment]
@sinhpn92, could you share the ad unit ID you use to make that ad request? Also, do you have a general idea what might be happening in the app prior to the crash?

Vu Chau
MoPub Tea,

**Comment by chauduyphanvu** [comment]
@sinhpn92, are you able to share an ad unit ID?

**Comment by chauduyphanvu** [comment]
Closing as irreproducible. Feel free to reopen if you are able to provide additional details I requested above.
