### ISSUE TITLE
Caused by java.lang.ClassNotFoundException at GooglePlayServicesAdapterConfiguration.initializeNetwork

### ISSUE THREAD

**Issue by pish11010** [mopub/mopub-android-sdk#438]
One line summary of the issue here

- [ o ] I am submitting a bug report for existing functionality
- [ o ] I visited https://developers.mopub.com/ and found no answer
- [ o ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ o ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
"com.mopub:mopub-sdk:5.14.0@aar"

#### Android Studio Version:
4.0

#### Gradle Version:
classpath 'com.android.tools.build:gradle:3.6.3'

#### Device model and OS Version:
52% Galaxy Tab A (2016)
31% Galaxy On7(2016)
11% Galaxy J7 Prime

67% Android 7
33% Android 8

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

I just got Crashlytics reports, I don't know well.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

`com.mopub.mobileads.GooglePlayServicesAdapterConfiguration.initializeNetwork(GooglePlayServicesAdapterConfiguration.java:69)` 

```
Caused by java.lang.ClassNotFoundException: Didn't find class "bpux" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/data/app/com.google.android.gms-1/base.apk", zip file "/data/app/com.google.android.gms-1/split_config.en.apk", zip file "/data/app/com.google.android.gms-1/split_config.tr.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-1/lib/arm, /data/app/com.google.android.gms-1/base.apk!/lib/armeabi-v7a, /data/app/com.google.android.gms-1/split_config.en.apk!/lib/armeabi-v7a, /data/app/com.google.android.gms-1/split_config.tr.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.google.android.gms.ads.internal.config.o.a(o.java:2)
       at com.google.android.gms.ads.MobileAdsSettingManagerCreatorImpl.getMobileAdsSettingManager(MobileAdsSettingManagerCreatorImpl.java:2)
       at com.google.android.gms.ads.internal.client.p.a(p.java:4)
       at cni.onTransact(cni.java:11)
       at android.os.Binder.transact(Binder.java:507)
       at com.google.android.gms.internal.ads.zzgi.transactAndReadException(zzgi.java:10)
       at com.google.android.gms.internal.ads.zzwt.zzb(zzwt.java:6)
       at com.google.android.gms.internal.ads.zzyj.zzh(zzyj.java:6)
       at com.google.android.gms.internal.ads.zzvc.zzpn(zzvc.java:7)
       at com.google.android.gms.internal.ads.zzvg.zzpq(zzvg.java:29)
       at com.google.android.gms.internal.ads.zzvg.zzd(zzvg.java:52)
       at com.google.android.gms.internal.ads.zzxw.zza(zzxw.java:20)
       at com.google.android.gms.ads.MobileAds.initialize(MobileAds.java:6)
       at com.google.android.gms.ads.MobileAds.initialize(MobileAds.java:8)
       at com.mopub.mobileads.GooglePlayServicesAdapterConfiguration.initializeNetwork(GooglePlayServicesAdapterConfiguration.java:69)
       at com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask.doInBackground(AdapterConfigurationManager.java:256)
       at com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask.doInBackground(AdapterConfigurationManager.java:182)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

```
Caused by java.lang.NoClassDefFoundError: Failed resolution of: Lbpux;
       at com.google.android.gms.ads.internal.config.o.a(o.java:2)
       at com.google.android.gms.ads.MobileAdsSettingManagerCreatorImpl.getMobileAdsSettingManager(MobileAdsSettingManagerCreatorImpl.java:2)
       at com.google.android.gms.ads.internal.client.p.a(p.java:4)
       at cni.onTransact(cni.java:11)
       at android.os.Binder.transact(Binder.java:507)
       at com.google.android.gms.internal.ads.zzgi.transactAndReadException(zzgi.java:10)
       at com.google.android.gms.internal.ads.zzwt.zzb(zzwt.java:6)
       at com.google.android.gms.internal.ads.zzyj.zzh(zzyj.java:6)
       at com.google.android.gms.internal.ads.zzvc.zzpn(zzvc.java:7)
       at com.google.android.gms.internal.ads.zzvg.zzpq(zzvg.java:29)
       at com.google.android.gms.internal.ads.zzvg.zzd(zzvg.java:52)
       at com.google.android.gms.internal.ads.zzxw.zza(zzxw.java:20)
       at com.google.android.gms.ads.MobileAds.initialize(MobileAds.java:6)
       at com.google.android.gms.ads.MobileAds.initialize(MobileAds.java:8)
       at com.mopub.mobileads.GooglePlayServicesAdapterConfiguration.initializeNetwork(GooglePlayServicesAdapterConfiguration.java:69)
       at com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask.doInBackground(AdapterConfigurationManager.java:256)
       at com.mopub.common.AdapterConfigurationManager$AdapterConfigurationsInitializationAsyncTask.doInBackground(AdapterConfigurationManager.java:182)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by pish11010** [comment]
I used 'com.mopub.mediation:admob:19.1.0'. 
I will try update mediation:admob version, to 19.5.0

**Comment by pish11010** [comment]
I upgraded to 'com.mopub.mediation:admob:19.4.0.0'
But this crash is reoccurrence.

**Comment by chauduyphanvu** [comment]
@pish11010, it looks like this crash originates from the Mobile Ads SDK (AdMob) during SDK initialization (triggered by [this line](https://github.com/mopub/mopub-android-mediation/blob/a483ed70a7a6538b7b012ab1e035e12e6242c6ef/AdMob/src/main/java/com/mopub/mobileads/GooglePlayServicesAdapterConfiguration.java#L69) in the adapter). Could you confirm you are using one of the [latest versions](https://developers.google.com/admob/android/rel-notes) for AdMob? 

Vu Chau
MoPub Team

**Comment by pish11010** [comment]
@chauduyphanvu
Thank you for replying me. 
I will try to use AdMob 19.5.0.

**Comment by chauduyphanvu** [comment]
@pish11010, closing this now. Feel free to reopen the issue if needed.
