### ISSUE TITLE
MoPubRecyclerAdapter crash because of unsafe cast

### ISSUE THREAD

**Issue by PauliusVal** [mopub/mopub-android-sdk#442]
MoPubRecyclerAdapter causes a crash if theme is applied to parent layout because of unsafe cast.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.14.0

#### Steps to reproduce the behavior:
1) Implement MoPubRecyclerAdapter for existing RecyclerView following MoPub guidelines
2) Apply theme (`android:theme="@style/Theme...`) to a layout containing RecyclerView
3) Scroll until first ad is loaded inside RecyclerView
4) App will crash here

#### Observed behavior:
MoPubRecyclerAdapter does unsafe context cast to Activity inside `onCreateViewHolder()` method call:
`return new MoPubRecyclerViewHolder(
                    adRenderer.createAdView((Activity) parent.getContext(), parent));`

#### Evidence:
`Fatal Exception: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
       at com.mopub.nativeads.MoPubRecyclerAdapter.onCreateViewHolder(MoPubRecyclerAdapter.java:414)
       at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
       at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
       at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
       at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
       at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
       at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
       at android.os.Handler.handleCallback(Handler.java:938)
`

**Comment by chauduyphanvu** [comment]
@PauliusVal, thanks for the info! Could you fork the sample app on this repo and make the necessary changes to trigger the same Exception? 

Vu Chau
MoPub Team

**Comment by PauliusVal** [comment]
Here you go: https://github.com/PauliusVal/mopub-android-sdk/commit/006d9088fb5c0a9bafd35e65ea591f66860d617e

**Comment by chauduyphanvu** [comment]
@PauliusVal, thanks! I was able to reproduce the crash and have let the rest of the team know. Stay tuned!

**Comment by chauduyphanvu** [comment]
This issue has been addressed in https://github.com/mopub/mopub-android-sdk/releases/tag/v5.16.0. Check it out and let us know if you continue seeing the issue!
