### ISSUE TITLE
Crashlytics reports a couple of errors with SDK of MoPub platform monetization

### ISSUE THREAD

**Issue by anonym24** [mopub/mopub-android-sdk#447]
#### Device model and OS Version: see screenshots from Crashlytics

`com.mopub.mobileads.VideoDownloader$VideoDownloaderTask.doInBackground` (`Caused by java.lang.OutOfMemoryError`)

`com.mopub.common.ClientMetadata.<init>` (`Caused by android.content.res.Resources$NotFoundException`)

**1:**
[![enter image description here][1]][1]

**2:**
[![enter image description here][2]][2]

p.s. I have those proguard settings set https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/proguard.txt for this SDK

  [1]: https://i.stack.imgur.com/nc0GA.png
  [2]: https://i.stack.imgur.com/j3X9X.png

**Comment by chauduyphanvu** [comment]
@anonym24, are you able to paste the raw stack trace(s) here? Thanks!

The OOM one is probably due to a burst cache. It could happen because you might have cached many video ads. Could you confirm if that is the case?

Vu Chau
MoPub Team

**Comment by anonym24** [comment]
@chauduyphanvu where to get those traces? This info is from Firebase Crashlytics (devices of users)

I have only one ad banner and one interstitial (fullscreen) ad in this app, so I don't think I do something wrong here, no additional settings were set

**Comment by chauduyphanvu** [comment]
@anonym24 - if you click on the `TXT` tab above the stack traces, you should be able to get the raw logs so it's easier to see the call stack.

Are you seeing the OOM crash on specific devices? Are also also requesting ads often without showing them? If that's the case, we recommend spacing the requests out over a longer time interval, so that cached ads get to display and you won't often have a big cache to worry about.

**Comment by anonym24** [comment]
@chauduyphanvu 

> Are you seeing the OOM crash on specific devices? 
What do you mean? Devices are reported by Crashlytics, it's not mine devices

> if you click on the TXT tab above the stack traces
could not found them these days

I updated to 5.15 version.

But here's another:

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.helge.kpopyoutube/com.mopub.mobileads.MoPubFullscreenActivity}: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
```
<details>
  <summary>TXT</summary>
```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{HidMyPackage/com.mopub.mobileads.MoPubFullscreenActivity}: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{HidMyPackage/com.mopub.mobileads.MoPubFullscreenActivity}: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2668)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6138)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by android.util.AndroidRuntimeException
java.lang.reflect.InvocationTargetException
Caused by android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:204)
       at android.webkit.WebView.getFactory(WebView.java:2341)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2336)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2395)
       at android.view.View.<init>(View.java:4180)
       at android.view.View.<init>(View.java:4303)
       at android.view.ViewGroup.<init>(ViewGroup.java:579)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
       at android.webkit.WebView.<init>(WebView.java:627)
       at android.webkit.WebView.<init>(WebView.java:572)
       at android.webkit.WebView.<init>(WebView.java:555)
       at android.webkit.WebView.<init>(WebView.java:542)
       at android.webkit.WebView.<init>(WebView.java:532)
       at com.mopub.mobileads.BaseWebView.<init>(BaseWebView.java:37)
       at com.mopub.mobileads.BaseWebViewViewability.<init>(BaseWebViewViewability.java:33)
       at com.mopub.mraid.MraidBridge$MraidWebView.<init>(MraidBridge.java:249)
       at com.mopub.mraid.MraidController.createWebView(MraidController.java:939)
       at com.mopub.mobileads.MoPubWebViewController.fillContent(MoPubWebViewController.java:87)
       at com.mopub.mobileads.FullscreenAdController.<init>(FullscreenAdController.java:166)
       at com.mopub.mobileads.MoPubFullscreenActivity.onCreate(MoPubFullscreenActivity.java:74)
       at android.app.Activity.performCreate(Activity.java:6787)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1148)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6138)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by java.lang.reflect.InvocationTargetException
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:198)
       at android.webkit.WebView.getFactory(WebView.java:2341)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2336)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2395)
       at android.view.View.<init>(View.java:4180)
       at android.view.View.<init>(View.java:4303)
       at android.view.ViewGroup.<init>(ViewGroup.java:579)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
       at android.webkit.WebView.<init>(WebView.java:627)
       at android.webkit.WebView.<init>(WebView.java:572)
       at android.webkit.WebView.<init>(WebView.java:555)
       at android.webkit.WebView.<init>(WebView.java:542)
       at android.webkit.WebView.<init>(WebView.java:532)
       at com.mopub.mobileads.BaseWebView.<init>(BaseWebView.java:37)
       at com.mopub.mobileads.BaseWebViewViewability.<init>(BaseWebViewViewability.java:33)
       at com.mopub.mraid.MraidBridge$MraidWebView.<init>(MraidBridge.java:249)
       at com.mopub.mraid.MraidController.createWebView(MraidController.java:939)
       at com.mopub.mobileads.MoPubWebViewController.fillContent(MoPubWebViewController.java:87)
       at com.mopub.mobileads.FullscreenAdController.<init>(FullscreenAdController.java:166)
       at com.mopub.mobileads.MoPubFullscreenActivity.onCreate(MoPubFullscreenActivity.java:74)
       at android.app.Activity.performCreate(Activity.java:6787)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1148)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6138)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by oH0
errorCode=2
Caused by oH0: errorCode=2
       at hH0.g(hH0.java:21)
       at hH0.i(hH0.java:5)
       at org.chromium.android_webview.AwBrowserProcess.h(AwBrowserProcess.java:9)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.e(WebViewChromiumFactoryProvider.java:80)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:12)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:198)
       at android.webkit.WebView.getFactory(WebView.java:2341)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2336)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2395)
       at android.view.View.<init>(View.java:4180)
       at android.view.View.<init>(View.java:4303)
       at android.view.ViewGroup.<init>(ViewGroup.java:579)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
       at android.webkit.WebView.<init>(WebView.java:627)
       at android.webkit.WebView.<init>(WebView.java:572)
       at android.webkit.WebView.<init>(WebView.java:555)
       at android.webkit.WebView.<init>(WebView.java:542)
       at android.webkit.WebView.<init>(WebView.java:532)
       at com.mopub.mobileads.BaseWebView.<init>(BaseWebView.java:37)
       at com.mopub.mobileads.BaseWebViewViewability.<init>(BaseWebViewViewability.java:33)
       at com.mopub.mraid.MraidBridge$MraidWebView.<init>(MraidBridge.java:249)
       at com.mopub.mraid.MraidController.createWebView(MraidController.java:939)
       at com.mopub.mobileads.MoPubWebViewController.fillContent(MoPubWebViewController.java:87)
       at com.mopub.mobileads.FullscreenAdController.<init>(FullscreenAdController.java:166)
       at com.mopub.mobileads.MoPubFullscreenActivity.onCreate(MoPubFullscreenActivity.java:74)
       at android.app.Activity.performCreate(Activity.java:6787)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1148)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6138)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by java.lang.UnsatisfiedLinkError
dlopen failed: "/data/app/com.android.chrome-1/lib/arm/libmonochrome.so" has unexpected e_machine: 40
Caused by java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.android.chrome-1/lib/arm/libmonochrome.so" has unexpected e_machine: 40
       at java.lang.Runtime.loadLibrary0(Runtime.java:999)
       at java.lang.System.loadLibrary(System.java:1562)
       at hH0.g(hH0.java:13)
       at hH0.i(hH0.java:5)
       at org.chromium.android_webview.AwBrowserProcess.h(AwBrowserProcess.java:9)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.e(WebViewChromiumFactoryProvider.java:80)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:12)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:198)
       at android.webkit.WebView.getFactory(WebView.java:2341)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2336)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2395)
       at android.view.View.<init>(View.java:4180)
       at android.view.View.<init>(View.java:4303)
       at android.view.ViewGroup.<init>(ViewGroup.java:579)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
       at android.webkit.WebView.<init>(WebView.java:627)
       at android.webkit.WebView.<init>(WebView.java:572)
       at android.webkit.WebView.<init>(WebView.java:555)
       at android.webkit.WebView.<init>(WebView.java:542)
       at android.webkit.WebView.<init>(WebView.java:532)
       at com.mopub.mobileads.BaseWebView.<init>(BaseWebView.java:37)
       at com.mopub.mobileads.BaseWebViewViewability.<init>(BaseWebViewViewability.java:33)
       at com.mopub.mraid.MraidBridge$MraidWebView.<init>(MraidBridge.java:249)
       at com.mopub.mraid.MraidController.createWebView(MraidController.java:939)
       at com.mopub.mobileads.MoPubWebViewController.fillContent(MoPubWebViewController.java:87)
       at com.mopub.mobileads.FullscreenAdController.<init>(FullscreenAdController.java:166)
       at com.mopub.mobileads.MoPubFullscreenActivity.onCreate(MoPubFullscreenActivity.java:74)
       at android.app.Activity.performCreate(Activity.java:6787)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1148)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6138)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

```
</details>

**Comment by chauduyphanvu** [comment]
This crash is happening because the WebView is updated while MoPub is trying to use it to show an ad. This is an issue with WebView's and Android's code. More info: https://bugs.chromium.org/p/chromium/issues/detail?id=506369.
