### ISSUE TITLE
NullPointerException on every Intersitial Ad

### ISSUE THREAD

**Issue by xabio** [mopub/mopub-android-sdk#448]
One line summary of the issue here
- [x ] I am submitting a bug report for existing functionality
- [ x] I visited https://developers.mopub.com/ and found no answer
- [ x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
com.mopub:mopub-sdk:5.15.0@aar
#### Android Studio Version:
4.0.1
#### Gradle Version:
'5.6.4' 
#### Device model and OS Version:
SAMSUNG AS5
#### Ad Unit IDs used in reproducing the issue:
Every adunit thay is intersitial with video
#### Steps to reproduce the behavior:
Load intersitial

#### Expected behavior:
No error in the 100% of intersitials
#### Observed behavior:
Null reference error 50% of the cases

#### Evidence:

```
 SdkConfiguration sdkConfiguration = new SdkConfiguration.Builder("b195f8dd8ded45fe847ad89ed1d016da")
                .withLogLevel(MoPubLog.LogLevel.DEBUG)
                .withLegitimateInterestAllowed(true)
                .build();

        MoPub.initializeSdk(Inicio.this, sdkConfiguration, new SdkInitializationListener() {
            @Override
            public void onInitializationFinished() {
                Log.d("Mopub", "SDK initialized");
                LoadAds();
            }
        });
```

```
public void LoadAds()
{
   Interstitial = new MoPubInterstitial(Inicio.this, AD_UNIT_INTERSITIAL_MOPUB);
   mInterstitial.setKeywords("XXX, XXX, XXX");
   mInterstitial.setInterstitialAdListener(Inicio.this);
   mInterstitial.load(); //HERE IT FAILS!!!
}

@Override
public void onInterstitialLoaded(MoPubInterstitial interstitial) {
    interstitial.show();       
}

```

020-12-11 23:42:40.951 1830-1830/com.kangaroo.XXXXXX/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kangaroo.XXXXX, PID: 1830
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kangaroo.XXXXXX/com.mopub.mobileads.MoPubFullscreenActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7814)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at androidx.media2.widget.MediaControlView.initTransportControls(MediaControlView.java:1473)
        at androidx.media2.widget.MediaControlView.initControllerView(MediaControlView.java:655)
        at androidx.media2.widget.MediaControlView.<init>(MediaControlView.java:289)
        at androidx.media2.widget.MediaControlView.<init>(MediaControlView.java:280)
        at androidx.media2.widget.MediaControlView.<init>(MediaControlView.java:276)
        at androidx.media2.widget.VideoView.initialize(VideoView.java:287)
        at androidx.media2.widget.VideoView.<init>(VideoView.java:225)
        at androidx.media2.widget.VideoView.<init>(VideoView.java:220)
        at androidx.media2.widget.VideoView.<init>(VideoView.java:216)
        at com.mopub.mobileads.factories.VideoViewFactory.internalCreate(VideoViewFactory.kt:18)
        at com.mopub.mobileads.factories.VideoViewFactory$Companion.create(VideoViewFactory.kt:15)
        at com.mopub.mobileads.VastVideoViewController.createVideoView(VastVideoViewController.kt:369)
        at com.mopub.mobileads.VastVideoViewController.<init>(VastVideoViewController.kt:196)
        at com.mopub.mobileads.FullscreenAdController.createVideoViewController(FullscreenAdController.java:221)
        at com.mopub.mobileads.FullscreenAdController.<init>(FullscreenAdController.java:176)
        at com.mopub.mobileads.MoPubFullscreenActivity.onCreate(MoPubFullscreenActivity.java:74)
        at android.app.Activity.performCreate(Activity.java:7955)
        at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7814) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by xabio** [comment]
Hi there,
We deployed to production, since with test Ids worked perfectly.
Next morning we got an awful surprise, hundreds of ARNs and exceptions in a
vast variety of devices, and consequently bad reviews..
Ad unit, which gave us the problem is 9ab6b24bc5284e2f9a7aedb2689e2926.

We downgraded to 5.11 since is not using androix.media library which seems
to be the problematic one.
Please, before releasing new versions ensure they work properly, since
experiencies like this force us to consider using another ad networks.

Regards.

**Comment by hmertkahraman** [comment]
Hi @xabio ,

Thank you for your feedback and the information you provided.

We currently don't have a known issue regarding this therefore we believe there might be an implementation issue which we'd like to resolve for you. Looking at your ad unit (considering its unchanged since then), we can deduce that it' might not be an ad source issue. So to further investigate and be able to guide you through your issue, can we additionally ask a few more questions:
- As the XML for view binding is problematic, could you double check whether `Inicio.this` is an Android `Activity` or not?
- Do you have the `media2` dependency to your Gradle? (See [here](https://github.com/mopub/mopub-android-sdk#requirements))
- It would be great if you can share your Gradle configuration with us so that we can see if a 3rd party dependency is perhaps interfering.

Thanks,
Mert
