### ISSUE TITLE
as reported by Farasy: Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent

### ISSUE THREAD

**Issue by dravyan** [mopub/mopub-android-sdk#462]
> 
> 
> I released a beta with 5.16.3 and the original issue is fixed but now there is a new one:
> 
> ```
> Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
>        at android.view.ViewGroup.addViewInner(ViewGroup.java:5327)
>        at android.view.ViewGroup.addView(ViewGroup.java:5156)
>        at android.view.ViewGroup.addView(ViewGroup.java:5096)
>        at android.view.ViewGroup.addView(ViewGroup.java:5069)
>        at com.mopub.mobileads.FullscreenAdController.onVideoFinish(FullscreenAdController.java:393)
>        at com.mopub.mobileads.VastVideoViewController$PlayerCallback.onPlaybackCompleted(VastVideoViewController.java:693)
>        at androidx.media2.player.MediaPlayer$Mp2Callback$6.callCallback(MediaPlayer.java:3434)
>        at androidx.media2.player.MediaPlayer$33.run(MediaPlayer.java:2969)
>        at android.os.Handler.handleCallback(Handler.java:900)
>        at android.os.Handler.dispatchMessage(Handler.java:103)
>        at android.os.Looper.loop(Looper.java:219)
>        at android.app.ActivityThread.main(ActivityThread.java:8387)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
> ```
> 
> It appears to be here:
> 
> ```
>             if (mVideoCtaButtonWidget != null) {
>                 relativeLayout.addView(mVideoCtaButtonWidget);
>             }
> ```

We see the same issue with 5.16.3 - very often.

_Originally posted by @Farasy in https://github.com/mopub/mopub-android-sdk/issues/460#issuecomment-808321239_

**Comment by dravyan** [comment]
The team has a fix for this crash and will be deploying it with the upcoming SDK release soon. We should have it live by the end of the week. Stay tuned!

Thanks,
MoPub Team
