### ISSUE TITLE
5.16.3 crash 

### ISSUE THREAD

**Issue by casolorz** [mopub/mopub-android-sdk#463]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version: 5.16.3

I don't have any way to reproduce the issue, has only happened on Crashlytics. The code at fault appears to be:

```
            if (mVideoCtaButtonWidget != null) {
                relativeLayout.addView(mVideoCtaButtonWidget);
            }
```

The exception:

```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5327)
       at android.view.ViewGroup.addView(ViewGroup.java:5156)
       at android.view.ViewGroup.addView(ViewGroup.java:5096)
       at android.view.ViewGroup.addView(ViewGroup.java:5069)
       at com.mopub.mobileads.FullscreenAdController.onVideoFinish(FullscreenAdController.java:393)
       at com.mopub.mobileads.VastVideoViewController$PlayerCallback.onPlaybackCompleted(VastVideoViewController.java:693)
       at androidx.media2.player.MediaPlayer$Mp2Callback$6.callCallback(MediaPlayer.java:3434)
       at androidx.media2.player.MediaPlayer$33.run(MediaPlayer.java:2969)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8387)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by rsatrasala** [comment]
Thank you @casolorz for reaching out. We are aware of the issue and investigating. Please follow the updates [here](https://github.com/mopub/mopub-android-sdk/issues/462)

**Comment by rsatrasala** [comment]
#462
