### ISSUE TITLE
MediaPlayer crash on 5.16

### ISSUE THREAD

**Issue by casolorz** [mopub/mopub-android-sdk#464]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version: 5.16.3

I only see this crash in Crashlytics. I do not see it with 5.15. I upgraded to 5.16 and started seeing the crash (also the parent view crash) so I moved back to 5.15 and the crash went away. When the parent view crash was fixed on 5.16.3 I moved to 5.16.3 and this crash started happening again. I don't use `androidx.media2.player.MediaPlayer` in my code. I have reported it to Google but they seem to think it would be very hard for their code to be causing the issue https://issuetracker.google.com/issues/182655822

Here is the exception:

```
Fatal Exception: java.lang.IllegalArgumentException: Receiver not registered: androidx.media2.player.d$b$b@2c96b18
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1499)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1604)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:678)
       at androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase.unregisterBecomingNoisyReceiverLocked(AudioFocusHandler.java:261)
       at androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase.onPause(AudioFocusHandler.java:161)
       at androidx.media2.player.AudioFocusHandler.onPause(AudioFocusHandler.java:76)
       at androidx.media2.player.MediaPlayer$3.onExecute(MediaPlayer.java:802)
       at androidx.media2.player.MediaPlayer$PendingFuture.execute(MediaPlayer.java:574)
       at androidx.media2.player.MediaPlayer.executePendingFutures(MediaPlayer.java:3268)
       at androidx.media2.player.MediaPlayer.addPendingFuture(MediaPlayer.java:730)
       at androidx.media2.player.MediaPlayer.pause(MediaPlayer.java:811)
       at androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase$AudioFocusListener.onAudioFocusChange(AudioFocusHandler.java:417)
       at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2667)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7860)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by dravyan** [comment]
Thank you. We will investigate and get back to you.

**Comment by casolorz** [comment]
It seems to happen with 5.15 as well, but much less than with 5.16. I'll keep monitoring to see if I find out anything else.

**Comment by Farasy** [comment]
> I've only seen it on Crashlytics. It seems to be happening on various devices. It gets reported on crashlytics as different exceptions per phone so it is hard to see all the devices but I've seen at least 3 brand and Android 7 through 10, but there are several other reports of the same crash I might not have clicked on yet.

Same here on multiple devices and Android versions.

**Comment by dravyan** [comment]
Fix has been applied for this issue and will be available in the next SDK release.

**Comment by dravyan** [comment]
MoPub SDK [v5.17.0 ](https://github.com/mopub/mopub-android-sdk/releases/tag/v5.17.0)is now live. Please update for the fix.

**Comment by casolorz** [comment]
I've only been using 5.17 in beta for a couple of days but so far no crashes like this.

**Comment by Farasy** [comment]
We see this same issue with 5.17.0 but as of now on Android 10 only

**Comment by casolorz** [comment]
I'm still seeing it as well but not as often as before 5.17.

```
Fatal Exception: java.lang.IllegalArgumentException: Receiver not registered: androidx.media2.player.AudioFocusHandler$b$b@f9e1d42
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1499)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1605)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:678)
       at androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase.unregisterBecomingNoisyReceiverLocked(AudioFocusHandler.java:261)
       at androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase.onPause(AudioFocusHandler.java:161)
       at androidx.media2.player.AudioFocusHandler.onPause(AudioFocusHandler.java:76)
       at androidx.media2.player.MediaPlayer$3.onExecute(MediaPlayer.java:802)
       at androidx.media2.player.MediaPlayer$PendingFuture.execute(MediaPlayer.java:574)
       at androidx.media2.player.MediaPlayer.executePendingFutures(MediaPlayer.java:3268)
       at androidx.media2.player.MediaPlayer.addPendingFuture(MediaPlayer.java:730)
       at androidx.media2.player.MediaPlayer.pause(MediaPlayer.java:811)
       at androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase$AudioFocusListener.onAudioFocusChange(AudioFocusHandler.java:447)
       at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2667)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8019)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by dravyan** [comment]
@casolorz, the issue has been reported and tracked on the Google issue tracker by other developers too. Feel free to track the update [here](https://issuetracker.google.com/issues/182655822). Thank you.

**Comment by agrobost** [comment]
This crash is still present on the version 5.18.0 on android 9/10/11 (and on huawei/samsung devices). I think you can reopen this issue.
![image](https://user-images.githubusercontent.com/14184466/134882001-9ab9e04f-4ed4-4047-bc4f-1354d7f4e5f7.png)
![image](https://user-images.githubusercontent.com/14184466/134882761-6e6835a1-4aba-47f3-a312-260cfa20f923.png)
![image](https://user-images.githubusercontent.com/14184466/134882821-6e22f215-074a-4135-911e-6e94b76a258b.png)
![image](https://user-images.githubusercontent.com/14184466/134882869-c7135c53-6915-4dc2-9bc7-d422b0c84a3f.png)

**Comment by casolorz** [comment]
This is one of my more common crashes still. It is affecting all sorts of phones but Crashlytics is grouping the crashes weird. This is one of the reported ones that has more phones:
![image](https://user-images.githubusercontent.com/1638377/134920533-035a2236-d282-4303-a1b9-bc2cdfb971ba.png)
