### ISSUE TITLE
Crash when showing the ad

### ISSUE THREAD

**Issue by OlegTarashkevich** [mopub/mopub-android-sdk#471]
I am getting crash reports in Crashlytics that the app crashes when showing ads.

#### MoPub SDK Version:
5.16.0

#### Android Studio Version:
4.1.3

#### Gradle Version:
4.0.0

#### Device model and OS Version:
Different devices

#### Steps to reproduce the behavior:
Not clear, just show the ad. 

#### Expected behavior:
Don't crash my apps while showing the ad!

#### Observed behavior:
I just receive a crash report in the Crashlytics.

#### Evidence:
Fatal Exception: java.lang.VerifyError: Verifier rejected class androidx.media2.player.MediaPlayer: com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a() failed to verify: com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(): [0x1A] monitor-exit on non-object (Conflict)
 com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(float) failed to verify: com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(float): [0x1A] monitor-exit on non-object (Conflict)
 com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(long) failed to verify: com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(long): [0x1E] monitor-exit on non-object (Conflict)
 com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(long, int) failed to verify: com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(long, int): [0x1F] monitor-exit on non-object (Conflict)
 com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(android.view.Surface) failed to verify: com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(android.view.Surface): [0x1A] monitor-exit on non-object (Conflict)
 com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(androidx.media.AudioAttributesCompat) failed to verify: com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(androidx.media.AudioAttributesCompat): [0x1C] monitor-exit on non-object (Conflict)
 com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(androidx.media2.common.MediaItem) failed to verify: com.google.common.util.concurrent.ListenableFuture androidx.media2.player.MediaPlayer.a(androidx.media2.common.MediaItem): [0x41] monitor-exit on non-object (Conflict)
 com.google.common.util.concurrent.ListenableFuture androidx.m<truncated: 2213 chars>
       at com.mopub.mobileads.factories.MediaPlayerFactory.internalCreate(MediaPlayerFactory.java:18)
       at com.mopub.mobileads.factories.MediaPlayerFactory$Companion.create(MediaPlayerFactory.java:15)
       at com.mopub.mobileads.VastVideoViewController.<init>(VastVideoViewController.java:77)
       at com.mopub.mobileads.FullscreenAdController.createVideoViewController(FullscreenAdController.java:325)
       at com.mopub.mobileads.FullscreenAdController.<init>(FullscreenAdController.java:210)
       at com.mopub.mobileads.MoPubFullscreenActivity.onCreate(MoPubFullscreenActivity.java:72)
       at android.app.Activity.performCreate(Activity.java:7893)
       at android.app.Activity.performCreate(Activity.java:7880)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3487)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7561)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

<img width="1152" alt="Screenshot 2021-04-18 at 12 11 06" src="https://user-images.githubusercontent.com/13828110/115140341-73232900-a03f-11eb-9727-bf2ff8dfa739.png">

**Comment by OlegTarashkevich** [comment]
Hi @chauduyphanvu @dravyan
Do we have any chances to fix this crash or may I temporarily turn off the Mopub ad in apps?

**Comment by chauduyphanvu** [comment]
@OlegTarashkevich, thanks for the report! It looks like the crash is originating from Google's `MediaPlayer`.

How are you integrating the MoPub SDK? If you integrate by manually dropping the SDK source into your project, you might need to declare [additional dependencies](https://github.com/mopub/mopub-android-sdk#requirements) required. Are you using the latest versions of all your dependencies?

Other than that, how are you requesting and showing ads? If we know a bit more about that, we can look into this issue more closely. 

Vu Chau
MoPub Team

**Comment by OlegTarashkevich** [comment]
@chauduyphanvu Thanks for the replay. I'm using v.5.16.0 and with Gradle (not manually):

moPubVer = '5.16.0' 

    implementation("com.mopub:mopub-sdk-banner:$moPubVer@aar") {
        transitive = true
    }

    implementation("com.mopub:mopub-sdk-fullscreen:$moPubVer@aar") {
        transitive = true
    }

I didn't update to 5.16.4 because I saw in your issues that it also has another bugs (playing ad in background).

Third-party dependencies loaded automatically.
Also I see that error related with **com.google.common.util.concurrent.ListenableFuture** 
I'm using next solution during the year and all was ok: https://stackoverflow.com/a/60492942/2946353
But starting from several month ago I updated Mopub sdk the crash starts again. I can't reproduce it, perhaps it appears randomly.

**Here are all the dependencies from my project:**
https://gist.github.com/OlegTarashkevich/4c333e732973777b935a01f974ea20a4#file-dependencies

How I show the interstitial ad:
https://gist.github.com/OlegTarashkevich/4c333e732973777b935a01f974ea20a4

Please help to resolve this issue asap.

**Comment by OlegTarashkevich** [comment]
@chauduyphanvu 
Should I rollback to v.5.14.0 ?
With 5.14.0 I didn't have the crash.

**Also I found another crash which starts to grow:**

Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5204)
       at android.view.ViewGroup.addView(ViewGroup.java:5027)
       at android.view.ViewGroup.addView(ViewGroup.java:4964)
       at android.view.ViewGroup.addView(ViewGroup.java:4937)
       at com.mopub.mobileads.FullscreenAdController.onVideoFinish(FullscreenAdController.java:377)
       at com.mopub.mobileads.VastVideoViewController$PlayerCallback.onPlaybackCompleted(VastVideoViewController.java:666)
       at androidx.media2.player.MediaPlayer$Mp2Callback$6.callCallback(MediaPlayer.java:3434)
       at androidx.media2.player.MediaPlayer$33.run(MediaPlayer.java:2969)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7561)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by chauduyphanvu** [comment]
> Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

This crash is fixed in 5.16.x.

I'm still looking into the original crash (`Fatal Exception: java.lang.VerifyError: Verifier rejected class androidx.media2.player.MediaPlayer`) but at this time there are no new findings on our part. 

Currently, the best recommendation is to upgrade to a 5.16.x version. The "video playing in the background" issue you mentioned earlier has not been verified.

**Comment by OlegTarashkevich** [comment]
Temporary I moved mopub ad to the last position of ad queue. This will help to decrease the crash.
Do you have a logic with internal ad crash reports in your android sdk? Perhaps it may help?

**Comment by chauduyphanvu** [comment]
@OlegTarashkevich, let us know if you continue seeing the crash after updating to 5.16.5. No, we do not collect crash reports from user devices. 

In the meantime, I have relayed the crash to the rest of the team. I'll update this thread if we have news to share.

**Comment by OlegTarashkevich** [comment]
@chauduyphanvu Hi,

I updated to v.5.17.0 and the app still sometimes crashes with the same error.

**Comment by chauduyphanvu** [comment]
@OlegTarashkevich, checking with the team. Stay tuned!

**Comment by C0deWithAj** [comment]
I am still getting this issue in version 5.18.0 . Any possible solution ?

**Comment by chauduyphanvu** [comment]
@C0deWithAj, thanks for checking in. We haven't gotten a reliable reproducible case to work with, so there haven't been any updates on this issue.

If you have any details to share to help us track down this crash, feel free to post them here. Thank!

**Comment by C0deWithAj** [comment]
@chauduyphanvu  The issue was happening on "5.18.0". Downgrading to 5.17.0 resolved the problem for now.
