### ISSUE TITLE
Bad URL noop at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:143)

### ISSUE THREAD

**Issue by husobe** [mopub/mopub-android-sdk#479]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Just showing ads but I am seeing this error below

2021-06-23 16:10:56.785 18133-18313/com.dwarfplanet.bundle.staging E/Volley: [73613] NetworkDispatcher.processRequest: Unhandled exception java.lang.RuntimeException: Bad URL noop
    java.lang.RuntimeException: Bad URL noop
        at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:143)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
     Caused by: java.net.MalformedURLException: no protocol: noop
        at java.net.URL.<init>(URL.java:601)
        at java.net.URL.<init>(URL.java:498)
        at java.net.URL.<init>(URL.java:447)
        at com.mopub.volley.toolbox.HurlStack.executeRequest(HurlStack.java:87)
        at com.mopub.network.RequestQueueHttpStack.executeRequest(RequestQueueHttpStack.java:57)
        at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:91)
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132) 
        at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) 
        at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:90) 

#### Expected behavior:
no error while requesting. we are thinking it is diminishing our impression counts. Our android impressions are way lower than ios.

#### Observed behavior:
the error above happens tens of times per session.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@husobe, this has been addressed in v5.16.0. Please update to the new SDK version.

Vu Chau
MoPub Team
