### ISSUE TITLE
Is this banner crash a MoPub issue or an issue with the custom adapter?

### ISSUE THREAD

**Issue by casolorz** [mopub/mopub-android-sdk#511]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version: 5.18.0

I've only seen this crash on Crashlytics so I don't have any more details and it hasn't happened to me on testing even when testing that ad network. I'm just wondering if I need to report this crash to Criteo or if it is on MoPub's end?

```
Fatal Exception: java.lang.IllegalStateException: Calling View methods on another thread than the UI thread.
       at com.android.webview.chromium.WebViewChromium.b(WebViewChromium.java:2)
       at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:15)
       at android.webkit.WebView.<init>(WebView.java:648)
       at android.webkit.WebView.<init>(WebView.java:577)
       at android.webkit.WebView.<init>(WebView.java:560)
       at android.webkit.WebView.<init>(WebView.java:547)
       at android.webkit.WebView.<init>(WebView.java:537)
       at com.criteo.publisher.CriteoBannerView.<init>(CriteoBannerView.java:127)
       at com.criteo.publisher.CriteoBannerView.<init>(CriteoBannerView.java:118)
       at com.criteo.mediation.mopub.CriteoBannerAdapter.load(CriteoBannerAdapter.java)
       at com.mopub.mobileads.BaseAd.internalLoad(BaseAd.java:104)
       at com.mopub.mobileads.AdAdapter.load(AdAdapter.java:84)
       at com.mopub.mobileads.AdViewController.loadBaseAd(AdViewController.java:845)
       at com.mopub.mobileads.AdViewController$3.onSettingsReceived(AdViewController.java:219)
       at com.mopub.common.CESettingsCacheService$getCESettings$cacheListener$1.onGetComplete(CESettingsCacheService.java:101)
       at com.mopub.common.CacheService$getFromDiskCacheAsync$$inlined$CoroutineExceptionHandler$1.handleException(CacheService.java:113)
       at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandlerKt.java:25)
       at kotlinx.coroutines.StandaloneCoroutine.handleJobException(StandaloneCoroutine.java:193)
       at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.java:229)
       at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.java:906)
       at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.java:863)
       at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.java:828)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:111)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:104)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

**Comment by p158276** [comment]
Hi @casolorz ,
Thanks for reaching out. From the error stack you provided, it seems the error happened in CriteoBannerView which is the custom adapter. You may want to reach out to the team and check about the adapter logic. 

Let us know if there's anything we can help with. 

Yoyo Lin
MoPub team

**Comment by casolorz** [comment]
Yes the stracktrace shows it is is there but should MoPub be calling the `load` method in the `CriteoBannerAdapter` outside the UI thread?

**Comment by p158276** [comment]
Hi @casolorz ,
You will need to keep it in the UI thread when requesting the ad. And we do keep in UI thread when logic related to show or render the ad.

**Comment by casolorz** [comment]
But if you look at the stacktrace, none of my code is there. It goes from some coroutines code to some sort of `CacheService` and then it calls the `load` method. So whatever is putting it outside the UI thread isn't my code and probably not Criteo's code.

**Comment by p158276** [comment]
Hi @casolorz ,
When calling the load method listed in the stack trace, it is in the main thread. It seems somehow happen when the network adapter tries to open up Android Webview. However, it is out of our scope to know how custom networks deal with their adapter with webView. You may want to open up an issue in their [Github repository](https://github.com/criteo/android-publisher-sdk) or contact Criteo.

**Comment by casolorz** [comment]
To me it looks like when `CacheService` gets the unhandled exception that it is on an IO thread and from there it does on to try to load the ad but I'll go ahead and report it to Criteo to see what they say. Thanks.

**Comment by TurpIF** [comment]
Hi there, I'm from Criteo, and I'll continue here as it will simplify the discussion, rather than having two parallel discussions.

I believe that the intuition from @casolorz is good, in the `CriteoBannerAdapter`, we're simply instantiating a `CriteoBannerView` which is a subclass of `WebView`, hence it's should be instantiated from the UI thread.

When developing the Criteo mediation adapter, we thought that it was guaranteed that the `BaseAd.load(Context, AdData)` method was called on the UI thread (so that adapters are not jumping themselves on the main thread).

So if it should only be called from UI thread, then I guess the error comes from before the `load` call, hence on MoPub side. If the `load` method can be called from a worker thread, then the error comes from our assumption and we should be able to jump on main thread in the adapter code.

@p158276 , could you confirm or infirm our assumption about `load` being only called on UI thread ?

**Comment by TurpIF** [comment]
Ok thank you for the precision. We will fix this wrong assumption on our adapter then.

**Comment by p158276** [comment]
Hi @casolorz , 
You're right. You should request the ad in the UI thread.
The error stack more likely to happen when the subsequent load happens and the CoroutineExceptionHandler might be invoked from an [arbitrary thread](https://github.com/Kotlin/kotlinx.coroutines/issues/839) which results in this exception. As we haven't gotten any report from our network partner, you can work with Criteo to update the adapter and see if the issue still persists.

**Comment by casolorz** [comment]
I have another exception that is very similar, also only on Crashlytics, it seems to be from the same `handleCoroutineException`. This time it seems to affect MoPub's own code, not a custom adapter. 

```
Fatal Exception: java.lang.RuntimeException: Exception while trying to handle coroutine exception
       at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandlerKt.java:38)
       at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandlerKt.java:29)
       at kotlinx.coroutines.StandaloneCoroutine.handleJobException(StandaloneCoroutine.java:193)
       at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.java:229)
       at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.java:906)
       at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.java:863)
       at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.java:828)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:111)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:104)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)

Caused by java.lang.IllegalStateException: getOmidVersion() must be called on the UI thread.
       at com.mopub.common.Preconditions.checkUiThreadInternal(Preconditions.java:288)
       at com.mopub.common.Preconditions.checkUiThread(Preconditions.java:111)
       at com.mopub.common.ViewabilityManager.getOmidVersion(ViewabilityManager.java:74)
       at com.mopub.common.AdUrlGenerator.setViewability(AdUrlGenerator.java:278)
       at com.mopub.common.AdUrlGenerator.addBaseParams(AdUrlGenerator.java:380)
       at com.mopub.mobileads.WebViewAdUrlGenerator.generateUrlString(WebViewAdUrlGenerator.java:26)
       at com.mopub.mobileads.AdViewController.generateAdUrl(AdViewController.java:657)
       at com.mopub.mobileads.AdViewController$4.onHashReceived(AdViewController.java:339)
       at com.mopub.common.CESettingsCacheService$getCESettingsHash$cacheListener$1.onGetComplete(CESettingsCacheService.java:61)
       at com.mopub.common.CacheService$getFromDiskCacheAsync$$inlined$CoroutineExceptionHandler$1.handleException(CacheService.java:113)
       at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandlerKt.java:25)
       at kotlinx.coroutines.StandaloneCoroutine.handleJobException(StandaloneCoroutine.java:193)
       at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.java:229)
       at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.java:906)
       at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.java:863)
       at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.java:828)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:111)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:104)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

**Comment by p158276** [comment]
Hi @casolorz ,
As this is another issue apart from the original one, can you raise another issue and provide detailed information(crash rate, affected os version, reproducible step)? Thanks.
