### ISSUE TITLE
Crash because some unhandled exception code is not on the UI Thread

### ISSUE THREAD

**Issue by casolorz** [mopub/mopub-android-sdk#513]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version: 5.18.0

I do not have a way to reproduce this issue, I've only seen it on crashlytics. It appears to be the same issue as https://github.com/mopub/mopub-android-sdk/issues/511

I looked briefly at the exception and at the code and it looks like something throws an unhandled exception and the `CoroutineExceptionHandler` on `CacheService` appears to handle that on a worker thread and then makes calls that require the UI thread. 

```
Fatal Exception: java.lang.RuntimeException: Exception while trying to handle coroutine exception
       at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandlerKt.java:38)
       at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandlerKt.java:29)
       at kotlinx.coroutines.StandaloneCoroutine.handleJobException(StandaloneCoroutine.java:193)
       at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.java:229)
       at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.java:906)
       at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.java:863)
       at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.java:828)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:111)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:104)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)

Caused by java.lang.IllegalStateException: getOmidVersion() must be called on the UI thread.
       at com.mopub.common.Preconditions.checkUiThreadInternal(Preconditions.java:288)
       at com.mopub.common.Preconditions.checkUiThread(Preconditions.java:111)
       at com.mopub.common.ViewabilityManager.getOmidVersion(ViewabilityManager.java:74)
       at com.mopub.common.AdUrlGenerator.setViewability(AdUrlGenerator.java:278)
       at com.mopub.common.AdUrlGenerator.addBaseParams(AdUrlGenerator.java:380)
       at com.mopub.mobileads.WebViewAdUrlGenerator.generateUrlString(WebViewAdUrlGenerator.java:26)
       at com.mopub.mobileads.AdViewController.generateAdUrl(AdViewController.java:657)
       at com.mopub.mobileads.AdViewController$4.onHashReceived(AdViewController.java:339)
       at com.mopub.common.CESettingsCacheService$getCESettingsHash$cacheListener$1.onGetComplete(CESettingsCacheService.java:61)
       at com.mopub.common.CacheService$getFromDiskCacheAsync$$inlined$CoroutineExceptionHandler$1.handleException(CacheService.java:113)
       at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandlerKt.java:25)
       at kotlinx.coroutines.StandaloneCoroutine.handleJobException(StandaloneCoroutine.java:193)
       at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.java:229)
       at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.java:906)
       at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.java:863)
       at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.java:828)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.java:111)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:104)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

**Comment by p158276** [comment]
Hi @casolorz ,
Thanks for filing the issue.  Meanwhile, can you provide the crash rate and affect Android OS version and device information? We'll circle back to our team and get back to you.

Thanks.
Yoyo Lin
MoPub Team

**Comment by casolorz** [comment]
It isn't happening to a huge amount of users, I think maybe under 200 crashes per week out of millions of users.

**Comment by p158276** [comment]
Hi @casolorz ,
Although there's no reproducible steps and the crash amount is low, the error is more likely to happen when the CoroutineExceptionHandler can be invoked from an arbitrary thread which results in this exception.  To way around this issue, you can modify SDK code to pop it back to the main thread.

1. Replace the CacheService exception line [161](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/common/CacheService.kt#L161) with CoroutineScope 
```
CoroutineScope(supervisorJob + Dispatchers.Main).launch {
    listener?.onPutComplete(false)
}
```

2. Replace the CacheService exception line [219](https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/common/CacheService.kt#L219) with CoroutineScope 
```
CoroutineScope(supervisorJob + Dispatchers.Main).launch {
    listener.onGetComplete(key, null)
}
```

**Comment by casolorz** [comment]
Since I just use the SDK from gradle, I can just wait until the next update. I'm assuming this will be changed? 
Thanks.

**Comment by p158276** [comment]
Hi @casolorz ,
There's no timeline for the next SDK release. You can wait until the next update or follow the step [here](https://developers.mopub.com/publishers/android/integrate/#option-2-zipped-source) to integrate through code source and modify it.

**Comment by casolorz** [comment]
Ok, thank you.
