### ISSUE TITLE
Strange crash logs when use mopub library

### ISSUE THREAD

**Issue by omihaz** [mopub/mopub-android-sdk#56]
Hello.

I'm not sure whether guilty this mopub library, but it is suspected.
On google play console I have crashlogs with webview, maybe its mopub webview, maybe not. I directly not use webview, just ads sdk's. 

Please check this logs.

1.
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java:903)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:283)
at android.webkit.CallbackProxy.uiOverrideUrlLoading(CallbackProxy.java:278)
at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:381)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4514)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
at dalvik.system.NativeStart.main(Native Method)

2.
java.lang.NullPointerException
at android.webkit.WebViewDatabase.initDatabase(WebViewDatabase.java:231)
at android.webkit.WebViewDatabase.init(WebViewDatabase.java:209)
at android.webkit.WebViewDatabase.access$000(WebViewDatabase.java:38)
at android.webkit.WebViewDatabase$1.run(WebViewDatabase.java:190)

3.
java.lang.NullPointerException
at android.webkit.WebView$SmoothRotateAnimationListener.onAnimationStart(WebView.java:8021)
at android.view.animation.Animation.getTransformation(Animation.java:761)
at android.view.ViewGroup.drawChild(ViewGroup.java:1655)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
at android.view.View.draw(View.java:6904)
at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
at android.view.ViewGroup.drawChild(ViewGroup.java:1788)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
at android.view.View.draw(View.java:6904)
at android.widget.FrameLayout.draw(FrameLayout.java:357)
at android.view.ViewGroup.drawChild(ViewGroup.java:1790)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1517)
at android.view.View.draw(View.java:6904)
at android.widget.FrameLayout.draw(FrameLayout.java:357)
at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1871)
at android.view.ViewRoot.draw(ViewRoot.java:1528)
at android.view.ViewRoot.performTraversals(ViewRoot.java:1264)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1868)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3697)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
at dalvik.system.NativeStart.main(Native Method)

4.
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@41e6d0d8 is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:797)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:265)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:73)
at android.app.Dialog.show(Dialog.java:282)
at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:862)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:175)
at android.app.ActivityThread.main(ActivityThread.java:5279)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)

**Comment by csbubbles** [comment]
Got a crash reported to Google Play Dev Console. Looks like MoPub caused that crash. That's the only log from there:

```
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java:1026)
at android.app.ContextImpl.startActivity(ContextImpl.java:1013)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:284)
at android.webkit.CallbackProxy.handleOverrideMessage(CallbackProxy.java:284)
at android.webkit.WebViewClassic.destroyJava(WebViewClassic.java:2329)
at android.webkit.WebViewClassic.destroy(WebViewClassic.java:2312)
at android.webkit.WebView.destroy(WebView.java:711)
at com.mopub.mobileads.BaseWebView.destroy(BaseWebView.java:75)
at com.mopub.mobileads.HtmlBanner.onInvalidate(HtmlBanner.java:81)
at com.mopub.mobileads.CustomEventBannerAdapter.invalidate(CustomEventBannerAdapter.java:118)
at com.mopub.mobileads.CustomEventBannerAdapter$1.run(CustomEventBannerAdapter.java:76)
at android.os.Handler.handleCallback(Handler.java:800)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5392)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
```

If it is as it looks like (MoPub crashed the app), then I would ask you to treat this issue as critical.

**Comment by MoJRen** [comment]
hi @csbubbles this was a known issue with the MoPub SDK that has been fixed. Do you know which SDK version produced this stack trace?

**Comment by csbubbles** [comment]
@MoJRen 

That's hard to tell. When I was integrating MoPub into my app, I downloaded .zip file (mopub-android-full-sdk.zip) from MoPub web console. I cannot find any references to a version in any files there. If there is some, please let me know where to look, and I will do.

**Comment by khchen428** [comment]
Hi @csbubbles - the version number should be located at https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/src/main/java/com/mopub/common/MoPub.java indicated by the SDK_VERSION string.

**Comment by csbubbles** [comment]
@MoJRen 

2.3

**Comment by danijoo** [comment]
Im using mopub 3.7.0 and im also affected by 1:

```
compile('com.mopub.sdk.android:mopub:3.7.0@aar') {
        transitive = true;
    }
```

```
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
       at android.app.ContextImpl.startActivity(ContextImpl.java:1026)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1013)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:284)
       at android.webkit.CallbackProxy.handleOverrideMessage(CallbackProxy.java:284)
       at android.webkit.WebViewClassic.destroyJava(WebViewClassic.java:2340)
       at android.webkit.WebViewClassic.destroy(WebViewClassic.java:2323)
       at android.webkit.WebView.destroy(WebView.java:711)
       at com.mopub.mobileads.BaseWebView.destroy(BaseWebView.java:62)
       at com.mopub.mobileads.HtmlBanner.onInvalidate(HtmlBanner.java:57)
       at com.mopub.mobileads.CustomEventBannerAdapter.invalidate(CustomEventBannerAdapter.java:93)
       at com.mopub.mobileads.CustomEventBannerAdapter$1.run(CustomEventBannerAdapter.java:54)
       at android.os.Handler.handleCallback(Handler.java:800)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5371)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
```
